import type { AlgorithmCase } from '../types'

export const threeByThreeAdvancedF2lCases: AlgorithmCase[] = [
  { name: "AF2L 1", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-1.svg", algorithm: "S R' S'" },
  { name: "AF2L 2", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-2.svg", algorithm: "L F' U2 F L'" },
  { name: "AF2L 3", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-3.svg", algorithm: "R U' R' U F' r U r'" },
  { name: "AF2L 4", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-4.svg", algorithm: "F R' F' R U R' U2 R" },
  { name: "AF2L 5", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-5.svg", algorithm: "R U R' U L U L'" },
  { name: "AF2L 6", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-6.svg", algorithm: "R U R' F U F'" },
  { name: "AF2L 7", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-7.svg", algorithm: "U' F' U' f R S'" },
  { name: "AF2L 8", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-8.svg", algorithm: "U' F' U2 L U L' F" },
  { name: "AF2L 9", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-9.svg", algorithm: "y' U R' U2 R U' R U R'" },
  { name: "AF2L 10", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-10.svg", algorithm: "U' R U R2 U' R" },
  { name: "AF2L 11", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-11.svg", algorithm: "U' R U' R' L U' L'" },
  { name: "AF2L 12", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-12.svg", algorithm: "U2 R U R' L' U L" },
  { name: "AF2L 13", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-13.svg", algorithm: "U R' F R F' R' U' R" },
  { name: "AF2L 14", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-14.svg", algorithm: "U' F R' F' R U L U L'" },
  { name: "AF2L 15", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-15.svg", algorithm: "U R' F R2 U' R' U2 F'" },
  { name: "AF2L 16", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-16.svg", algorithm: "U' F' R' U' R F" },
  { name: "AF2L 17", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-17.svg", algorithm: "U2 R B' U' B R'" },
  { name: "AF2L 18", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-18.svg", algorithm: "U F' U2 F L' U' L" },
  { name: "AF2L 19", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-19.svg", algorithm: "U' R U2 R' f R f'" },
  { name: "AF2L 20", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-20.svg", algorithm: "U R U R' L U L'" },
  { name: "AF2L 21", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-21.svg", algorithm: "U R F U F' R'" },
  { name: "AF2L 22", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-22.svg", algorithm: "R U' R2 U R" },
  { name: "AF2L 23", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-23.svg", algorithm: "L F' U F L'" },
  { name: "AF2L 24", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-24.svg", algorithm: "R U' R' U2 L' U L" },
  { name: "AF2L 25", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-25.svg", algorithm: "F' U R' U2 R F" },
  { name: "AF2L 26", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-26.svg", algorithm: "L R U2 R' L'" },
  { name: "AF2L 27", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-27.svg", algorithm: "R' F R2 U R' F'" },
  { name: "AF2L 28", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-28.svg", algorithm: "R U' R2 U' R U' R' U' R" },
  { name: "AF2L 29", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-29.svg", algorithm: "F' U L' U L U' L U L' F" },
  { name: "AF2L 30", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-30.svg", algorithm: "R U' R' U' L' U L U L' U' L" },
  { name: "AF2L 31", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-31.svg", algorithm: "R U R' U' R U' R' U R' U' R" },
  { name: "AF2L 32", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-32.svg", algorithm: "R U R' U' R U' R' f' L' f" },
  { name: "AF2L 33", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-33.svg", algorithm: "R U' R' U' L' U' L U' L' U L" },
  { name: "AF2L 34", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-34.svg", algorithm: "F' R' U R U' R' U' R F" },
  { name: "AF2L 35", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-35.svg", algorithm: "R U' R' U' R U R' L U' L'" },
  { name: "AF2L 36", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-36.svg", algorithm: "R' F R2 U' R' U' R U R' U2 F'" },
  { name: "AF2L 37", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-37.svg", algorithm: "R U R' U2 R U' R' f R f'" },
  { name: "AF2L 38", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-38.svg", algorithm: "R U' R' U R U2 R' L U2 L'" },
  { name: "AF2L 39", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-39.svg", algorithm: "R U R' d' L U' L' U L U L'" },
  { name: "AF2L 40", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-40.svg", algorithm: "R U' R2 U2 R U R' U2 R" },
  { name: "AF2L 41", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-41.svg", algorithm: "R U' R' d R' U2 R L' U L" },
  { name: "AF2L 42", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-42.svg", algorithm: "R U' R' U2 L' U2 L U2 L' U L" },
  { name: "AF2L 1a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-1a.svg", algorithm: "U2 R U' R' U' R' U' R" },
  { name: "AF2L 2a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-2a.svg", algorithm: "R' F R F' L U2 L'" },
  { name: "AF2L 3a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-3a.svg", algorithm: "R' F R2 U' R' U F'" },
  { name: "AF2L 4a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-4a.svg", algorithm: "U R U R2 U2 R" },
  { name: "AF2L 5a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-5a.svg", algorithm: "y U L' U L R' U2 R" },
  { name: "AF2L 6a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-6a.svg", algorithm: "U R L' U L R'" },
  { name: "AF2L 7a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-7a.svg", algorithm: "U2 R U' R' U2 R' U R" },
  { name: "AF2L 8a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-8a.svg", algorithm: "U2 R U' R' d L' U L" },
  { name: "AF2L 9a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-9a.svg", algorithm: "U2 R U' R' L' U L" },
  { name: "AF2L 10a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-10a.svg", algorithm: "U' R U' R' U f R' f'" },
  { name: "AF2L 11a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-11a.svg", algorithm: "U' R U R' y' U' L' U' L" },
  { name: "AF2L 12a", image: "/algorithms/3x3/advanced-f2l/advanced-f2l-af2l-12a.svg", algorithm: "U' R U' R' U2 F' r U r'" },
]
