import type { AlgorithmCase } from '../types'

export const threeByThreeCollCases: AlgorithmCase[] = [
  { name: "H1", image: "/algorithms/3x3/coll/coll-h1.png", algorithm: "R U R' U R U' R' U R U2 R'" },
  { name: "H2", image: "/algorithms/3x3/coll/coll-h2.png", algorithm: "F R U' R' U R U2 R' U' R U R' U' F'" },
  { name: "H3", image: "/algorithms/3x3/coll/coll-h3.png", algorithm: "R U R' U R U L' U R' U' L" },
  { name: "H4", image: "/algorithms/3x3/coll/coll-h4.png", algorithm: "F R U R' U' R U R' U' R U R' U' F'" },
  { name: "L1", image: "/algorithms/3x3/coll/coll-l1.png", algorithm: "R' U2 R U R' U' R U R' U' R U R' U R" },
  { name: "L2", image: "/algorithms/3x3/coll/coll-l2.png", algorithm: "R' U2 R' D' R U2 R' D R2" },
  { name: "L3", image: "/algorithms/3x3/coll/coll-l3.png", algorithm: "R U2 R D R' U2 R D' R2" },
  { name: "L4", image: "/algorithms/3x3/coll/coll-l4.png", algorithm: "F R' F' r U R U' r'" },
  { name: "L5", image: "/algorithms/3x3/coll/coll-l5.png", algorithm: "x R' U R D' R' U' R D" },
  { name: "L6", image: "/algorithms/3x3/coll/coll-l6.png", algorithm: "R' U' R U R' F' R U R' U' R' F R2" },
  { name: "P1", image: "/algorithms/3x3/coll/coll-p1.png", algorithm: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: "P2", image: "/algorithms/3x3/coll/coll-p2.png", algorithm: "R' F2 R U2 R U2 R' F2 U' R U' R'" },
  { name: "P3", image: "/algorithms/3x3/coll/coll-p3.png", algorithm: "R' U' F' R U R' U' R' F R2 U2 R' U2 R" },
  { name: "P4", image: "/algorithms/3x3/coll/coll-p4.png", algorithm: "R U R' U' R' F R2 U R' U' R U R' U' F'" },
  { name: "P5", image: "/algorithms/3x3/coll/coll-p5.png", algorithm: "R U' L' U R' U L U L' U L" },
  { name: "P6", image: "/algorithms/3x3/coll/coll-p6.png", algorithm: "R2 D' R U R' D R U R U' R' U R U R' U R" },
  { name: "T1", image: "/algorithms/3x3/coll/coll-t1.png", algorithm: "R U2 R' U' R U' R2 U2 R U R' U R" },
  { name: "T2", image: "/algorithms/3x3/coll/coll-t2.png", algorithm: "R' U R U2 R' L' U R U' L" },
  { name: "T3", image: "/algorithms/3x3/coll/coll-t3.png", algorithm: "l' U' L U l F' L' F" },
  { name: "T4", image: "/algorithms/3x3/coll/coll-t4.png", algorithm: "F R U R' U' R U' R' U' R U R' F'" },
  { name: "T5", image: "/algorithms/3x3/coll/coll-t5.png", algorithm: "r U R' U' r' F R F'" },
  { name: "T6", image: "/algorithms/3x3/coll/coll-t6.png", algorithm: "R' U R2 D r' U2 r D' R2 U' R" },
  { name: "U1", image: "/algorithms/3x3/coll/coll-u1.png", algorithm: "R' U' R U' R' U2 R2 U R' U R U2 R'" },
  { name: "U2", image: "/algorithms/3x3/coll/coll-u2.png", algorithm: "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R" },
  { name: "U3", image: "/algorithms/3x3/coll/coll-u3.png", algorithm: "R2 D R' U2 R D' R' U2 R'" },
  { name: "U4", image: "/algorithms/3x3/coll/coll-u4.png", algorithm: "F R U' R' U R U R' U R U' R' F'" },
  { name: "U5", image: "/algorithms/3x3/coll/coll-u5.png", algorithm: "R2 D' R U2 R' D R U2 R" },
  { name: "U6", image: "/algorithms/3x3/coll/coll-u6.png", algorithm: "R2 D' R U R' D R U R U' R' U' R" },
]
