import type { AlgorithmCase } from '../types'

export const threeByThreeF2lCases: AlgorithmCase[] = [
  { name: "F2L 1", image: "/algorithms/3x3/f2l/f2l-f2l-1.svg", algorithm: "U R U' R'" },
  { name: "F2L 2", image: "/algorithms/3x3/f2l/f2l-f2l-2.svg", algorithm: "F R' F' R" },
  { name: "F2L 3", image: "/algorithms/3x3/f2l/f2l-f2l-3.svg", algorithm: "F' U' F" },
  { name: "F2L 4", image: "/algorithms/3x3/f2l/f2l-f2l-4.svg", algorithm: "R U R'" },
  { name: "F2L 5", image: "/algorithms/3x3/f2l/f2l-f2l-5.svg", algorithm: "U' R U R' U2 R U' R'" },
  { name: "F2L 6", image: "/algorithms/3x3/f2l/f2l-f2l-6.svg", algorithm: "U' r U' R' U R U r'" },
  { name: "F2L 7", image: "/algorithms/3x3/f2l/f2l-f2l-7.svg", algorithm: "U' R U2 R' U' R U2 R'" },
  { name: "F2L 8", image: "/algorithms/3x3/f2l/f2l-f2l-8.svg", algorithm: "d R' U2 R U R' U2 R" },
  { name: "F2L 9", image: "/algorithms/3x3/f2l/f2l-f2l-9.svg", algorithm: "U' R U' R' U F' U' F" },
  { name: "F2L 10", image: "/algorithms/3x3/f2l/f2l-f2l-10.svg", algorithm: "U' R U R' U R U R'" },
  { name: "F2L 11", image: "/algorithms/3x3/f2l/f2l-f2l-11.svg", algorithm: "U' R U2 R' U F' U' F" },
  { name: "F2L 12", image: "/algorithms/3x3/f2l/f2l-f2l-12.svg", algorithm: "R U' R' U R U' R' U2 R U' R'" },
  { name: "F2L 13", image: "/algorithms/3x3/f2l/f2l-f2l-13.svg", algorithm: "y' U R' U R U' R' U' R" },
  { name: "F2L 14", image: "/algorithms/3x3/f2l/f2l-f2l-14.svg", algorithm: "U' R U' R' U R U R'" },
  { name: "F2L 15", image: "/algorithms/3x3/f2l/f2l-f2l-15.svg", algorithm: "R' D' R U' R' D R U R U' R'" },
  { name: "F2L 16", image: "/algorithms/3x3/f2l/f2l-f2l-16.svg", algorithm: "R U' R' U2 F' U' F" },
  { name: "F2L 17", image: "/algorithms/3x3/f2l/f2l-f2l-17.svg", algorithm: "R U2 R' U' R U R'" },
  { name: "F2L 18", image: "/algorithms/3x3/f2l/f2l-f2l-18.svg", algorithm: "y' R' U2 R U R' U' R" },
  { name: "F2L 19", image: "/algorithms/3x3/f2l/f2l-f2l-19.svg", algorithm: "U R U2 R' U R U' R'" },
  { name: "F2L 20", image: "/algorithms/3x3/f2l/f2l-f2l-20.svg", algorithm: "y' U' R' U2 R U' R' U R" },
  { name: "F2L 21", image: "/algorithms/3x3/f2l/f2l-f2l-21.svg", algorithm: "U2 R U R' U R U' R'" },
  { name: "F2L 22", image: "/algorithms/3x3/f2l/f2l-f2l-22.svg", algorithm: "r U' r' U2 r U r'" },
  { name: "F2L 23", image: "/algorithms/3x3/f2l/f2l-f2l-23.svg", algorithm: "U R U' R' U' R U' R' U R U' R'" },
  { name: "F2L 24", image: "/algorithms/3x3/f2l/f2l-f2l-24.svg", algorithm: "F U R U' R' F' R U' R'" },
  { name: "F2L 25", image: "/algorithms/3x3/f2l/f2l-f2l-25.svg", algorithm: "U' R' F R F' R U R'" },
  { name: "F2L 26", image: "/algorithms/3x3/f2l/f2l-f2l-26.svg", algorithm: "U R U' R' F R' F' R" },
  { name: "F2L 27", image: "/algorithms/3x3/f2l/f2l-f2l-27.svg", algorithm: "R U' R' U R U' R'" },
  { name: "F2L 28", image: "/algorithms/3x3/f2l/f2l-f2l-28.svg", algorithm: "R U R' U' F R' F' R" },
  { name: "F2L 29", image: "/algorithms/3x3/f2l/f2l-f2l-29.svg", algorithm: "R' F R F' U R U' R'" },
  { name: "F2L 30", image: "/algorithms/3x3/f2l/f2l-f2l-30.svg", algorithm: "R U R' U' R U R'" },
  { name: "F2L 31", image: "/algorithms/3x3/f2l/f2l-f2l-31.svg", algorithm: "U' R' F R F' R U' R'" },
  { name: "F2L 32", image: "/algorithms/3x3/f2l/f2l-f2l-32.svg", algorithm: "U R U' R' U R U' R' U R U' R'" },
  { name: "F2L 33", image: "/algorithms/3x3/f2l/f2l-f2l-33.svg", algorithm: "U' R U' R' U2 R U' R'" },
  { name: "F2L 34", image: "/algorithms/3x3/f2l/f2l-f2l-34.svg", algorithm: "U R U R' U2 R U R'" },
  { name: "F2L 35", image: "/algorithms/3x3/f2l/f2l-f2l-35.svg", algorithm: "U' R U R' U F' U' F" },
  { name: "F2L 36", image: "/algorithms/3x3/f2l/f2l-f2l-36.svg", algorithm: "U F' U' F U' R U R'" },
  { name: "F2L 37", image: "/algorithms/3x3/f2l/f2l-f2l-37.svg", algorithm: "R2 U2 F R2 F' U2 R' U R'" },
  { name: "F2L 38", image: "/algorithms/3x3/f2l/f2l-f2l-38.svg", algorithm: "R U' R' U' R U R' U2 R U' R'" },
  { name: "F2L 39", image: "/algorithms/3x3/f2l/f2l-f2l-39.svg", algorithm: "R U' R' U R U2 R' U R U' R'" },
  { name: "F2L 40", image: "/algorithms/3x3/f2l/f2l-f2l-40.svg", algorithm: "r U' r' U2 r U r' R U R'" },
  { name: "F2L 41", image: "/algorithms/3x3/f2l/f2l-f2l-41.svg", algorithm: "R U' R' r U' r' U2 r U r'" },
]
