import type { AlgorithmCase } from '../types'

export const threeByThreeVlsUbUlCases: AlgorithmCase[] = [
  { name: "VLS 56", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-56.svg", algorithm: "y' U R D r' U' r D' R'" },
  { name: "VLS 57", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-57.svg", algorithm: "U S' R U' R' S" },
  { name: "VLS 58", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-58.svg", algorithm: "U x' U' R U x U' R' U' R' U R" },
  { name: "VLS 59", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-59.svg", algorithm: "y' U S R U R' U' R' S'" },
  { name: "VLS 60", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-60.svg", algorithm: "U2 R U' R' y R' F R U' R' F' R" },
  { name: "VLS 61", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-61.svg", algorithm: "U R U R' U' F' L' U' L F" },
  { name: "VLS 62", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-62.svg", algorithm: "U R U' R2 U' y' R' U2 R U R' U' R B" },
  { name: "VLS 63", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-63.svg", algorithm: "U R U R2 U' R U' R' U2 F R F'" },
  { name: "VLS 64", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-64.svg", algorithm: "U R U R' U2 R' U' F U R U' F'" },
  { name: "VLS 65", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-65.svg", algorithm: "U R U' R2 F' U' F U' R U R' U R" },
  { name: "VLS 66", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-66.svg", algorithm: "U R U R' U' R U R' U' F' U F R U' R'" },
  { name: "VLS 67", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-67.svg", algorithm: "U R U' R' U R U R' U' R' F R F'" },
  { name: "VLS 68", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-68.svg", algorithm: "U2 F R' F' R U' R U' R'" },
  { name: "VLS 69", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-69.svg", algorithm: "U2 F' r U2 R' U r' F2 R" },
  { name: "VLS 70", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-70.svg", algorithm: "U2 R U2 r2 F' r U' L' U2 L U' M'" },
  { name: "VLS 71", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-71.svg", algorithm: "U2 F R' F' R2 U2 R'" },
  { name: "VLS 72", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-72.svg", algorithm: "U2 r U R' U' M U R U R'" },
  { name: "VLS 73", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-73.svg", algorithm: "U f' U f U' R' U2 R' U2 R" },
  { name: "VLS 74", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-74.svg", algorithm: "U R U' R2 F' U' F U R" },
  { name: "VLS 75", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-75.svg", algorithm: "U2 R U2 R' U R' U' F' U F R" },
  { name: "VLS 76", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-76.svg", algorithm: "R U R' F' U2 F R U2 R'" },
  { name: "VLS 77", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-77.svg", algorithm: "U2 R U' R' d R2 F R F' R" },
  { name: "VLS 78", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-78.svg", algorithm: "U2 R d' R U' R' F'" },
  { name: "VLS 79", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-79.svg", algorithm: "U2 R' U' R2 y R U' R2 F' R2 U' R'" },
  { name: "VLS 80", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-80.svg", algorithm: "U2 F R' F' R2 U' R' U R U2 R'" },
  { name: "VLS 81", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-81.svg", algorithm: "U2 R U2 R' U l' U l2 U' l2 U' l2 U l'" },
  { name: "VLS 82", image: "/algorithms/3x3/vls-ub-ul/vls-ub-ul-vls-82.svg", algorithm: "U2 R' U' F' U F R U R U2 R'" },
]
