import type { AlgorithmCase } from '../../types'

export const threeByThreeVlsUfUlCases: AlgorithmCase[] = [
  { name: "VLS 137", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-137.svg", algorithm: "U2 F R' F' R U2 R' F R F'" },
  { name: "VLS 138", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-138.svg", algorithm: "U' F R' F' R2 U' R' U2 R U' R' U R U' R'" },
  { name: "VLS 139", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-139.svg", algorithm: "U2 R U' R' U' R U' R' F' U' F R U R'" },
  { name: "VLS 140", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-140.svg", algorithm: "U2 R U' R2 F' U' F U R2 U2 R'" },
  { name: "VLS 141", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-141.svg", algorithm: "U L' U2 R U R' L U F R U R' F'" },
  { name: "VLS 142", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-142.svg", algorithm: "y' U R2 D' r U' r' D R2" },
  { name: "VLS 143", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-143.svg", algorithm: "R' U' F U R2 U' R' F'" },
  { name: "VLS 144", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-144.svg", algorithm: "M' U2 R U' R' U R U2 r'" },
  { name: "VLS 145", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-145.svg", algorithm: "U R U R' U' R U' R' F R U R' U' F'" },
  { name: "VLS 146", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-146.svg", algorithm: "R' U' F U' R2 U R2 U R F'" },
  { name: "VLS 147", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-147.svg", algorithm: "U R U R' U2 R' F R F'" },
  { name: "VLS 148", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-148.svg", algorithm: "U2 R U2 R2 F R2 B' R2 F' R2 B R'" },
  { name: "VLS 149", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-149.svg", algorithm: "R' F R2 U' R' U2 R U R' F'" },
  { name: "VLS 150", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-150.svg", algorithm: "U F2 u' r U r' D R U2 R" },
  { name: "VLS 151", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-151.svg", algorithm: "U2 R U' R' U' R' F R2 U R' U' F'" },
  { name: "VLS 152", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-152.svg", algorithm: "U2 R U' R' U R U' R' U' R' F R F'" },
  { name: "VLS 153", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-153.svg", algorithm: "M2 U2 R' F R2 U2 r2 F R" },
  { name: "VLS 154", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-154.svg", algorithm: "U R' F' r U' r' F2 R U F R' F' R" },
  { name: "VLS 155", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-155.svg", algorithm: "R2 U2 R2 U2 R' F R2 F' U2 R'" },
  { name: "VLS 156", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-156.svg", algorithm: "U2 R U2 R' F U R U' R' F'" },
  { name: "VLS 157", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-157.svg", algorithm: "U2 R' U' R U' R' U2 F R2 U R' U' F'" },
  { name: "VLS 158", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-158.svg", algorithm: "U R' U' R2 U' R2 U2 R U2 R' F R F'" },
  { name: "VLS 159", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-159.svg", algorithm: "U2 R U' R' U R U2 R' F R U R' U' F'" },
  { name: "VLS 160", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-160.svg", algorithm: "R' F R F' R U2 R' U2 R' F R F'" },
  { name: "VLS 161", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-161.svg", algorithm: "U' F' U F R U' R2 F R F'" },
  { name: "VLS 162", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-162.svg", algorithm: "R' F R2 U' R' U R U2 R' U' F'" },
  { name: "VLS 163", image: "/algorithms/3x3/vls-uf-ul/vls-uf-ul-vls-163.svg", algorithm: "U R U' M' U2 R' U' R U R' U2 M U R U' R'" },
]
