import type { AlgorithmCase } from '../types'

export const threeByThreeVlsUfCases: AlgorithmCase[] = [
  { name: "VLS 83", image: "/algorithms/3x3/vls-uf/vls-uf-vls-83.svg", algorithm: "U F' U' F U R U2 R'" },
  { name: "VLS 84", image: "/algorithms/3x3/vls-uf/vls-uf-vls-84.svg", algorithm: "M' U R U' r'" },
  { name: "VLS 85", image: "/algorithms/3x3/vls-uf/vls-uf-vls-85.svg", algorithm: "F2 r U r' F U' R U R'" },
  { name: "VLS 86", image: "/algorithms/3x3/vls-uf/vls-uf-vls-86.svg", algorithm: "U R' U' R' F R U R U' F'" },
  { name: "VLS 87", image: "/algorithms/3x3/vls-uf/vls-uf-vls-87.svg", algorithm: "M' U l F' U2 L' U' L U' L'" },
  { name: "VLS 88", image: "/algorithms/3x3/vls-uf/vls-uf-vls-88.svg", algorithm: "U R U' R' F R U R' U' F'" },
  { name: "VLS 89", image: "/algorithms/3x3/vls-uf/vls-uf-vls-89.svg", algorithm: "R' F R2 B' R' F' R B R'" },
  { name: "VLS 90", image: "/algorithms/3x3/vls-uf/vls-uf-vls-90.svg", algorithm: "M' U' r' F2 R F' U L' U L" },
  { name: "VLS 91", image: "/algorithms/3x3/vls-uf/vls-uf-vls-91.svg", algorithm: "y' R' U' R U' R' U R' F' U' F U R2" },
  { name: "VLS 92", image: "/algorithms/3x3/vls-uf/vls-uf-vls-92.svg", algorithm: "U R U R' U2 R' F R2 U R' U' F'" },
  { name: "VLS 93", image: "/algorithms/3x3/vls-uf/vls-uf-vls-93.svg", algorithm: "U2 r' U' R2 U' R2 U2 r" },
  { name: "VLS 94", image: "/algorithms/3x3/vls-uf/vls-uf-vls-94.svg", algorithm: "U F' U' F d S R2 F R F' R S'" },
  { name: "VLS 95", image: "/algorithms/3x3/vls-uf/vls-uf-vls-95.svg", algorithm: "U F' R' U' R F R' U R2 U2 R'" },
  { name: "VLS 96", image: "/algorithms/3x3/vls-uf/vls-uf-vls-96.svg", algorithm: "R' F R F' U R' U' R' D' R U R' D R2" },
  { name: "VLS 97", image: "/algorithms/3x3/vls-uf/vls-uf-vls-97.svg", algorithm: "R' F R F'" },
  { name: "VLS 98", image: "/algorithms/3x3/vls-uf/vls-uf-vls-98.svg", algorithm: "U R U' R' U' R' F' U' F U R" },
  { name: "VLS 99", image: "/algorithms/3x3/vls-uf/vls-uf-vls-99.svg", algorithm: "R' F R F' R U R' U R U2 R'" },
  { name: "VLS 100", image: "/algorithms/3x3/vls-uf/vls-uf-vls-100.svg", algorithm: "U R U' R' U2 R U R' U' R' F R F'" },
  { name: "VLS 101", image: "/algorithms/3x3/vls-uf/vls-uf-vls-101.svg", algorithm: "U R' U' R' F R2 F' R' U R" },
  { name: "VLS 102", image: "/algorithms/3x3/vls-uf/vls-uf-vls-102.svg", algorithm: "U F' L' U2 L U L' U' L U F" },
  { name: "VLS 103", image: "/algorithms/3x3/vls-uf/vls-uf-vls-103.svg", algorithm: "R' F R F' R2 D' R U2 R' D R U2 R" },
  { name: "VLS 104", image: "/algorithms/3x3/vls-uf/vls-uf-vls-104.svg", algorithm: "R' F R2 F' r U R' U' r'" },
  { name: "VLS 105", image: "/algorithms/3x3/vls-uf/vls-uf-vls-105.svg", algorithm: "F' U' F R' F R F' R U R'" },
  { name: "VLS 106", image: "/algorithms/3x3/vls-uf/vls-uf-vls-106.svg", algorithm: "R' F R U2 y' R' U' R U' R'" },
  { name: "VLS 107", image: "/algorithms/3x3/vls-uf/vls-uf-vls-107.svg", algorithm: "R' F R F' U R' U' R U' R' U2 R" },
  { name: "VLS 108", image: "/algorithms/3x3/vls-uf/vls-uf-vls-108.svg", algorithm: "U' F' U' F U2 R' F R F'" },
  { name: "VLS 109", image: "/algorithms/3x3/vls-uf/vls-uf-vls-109.svg", algorithm: "R' F R F2 r U R' U' r' F R" },
]
