import type { AlgorithmCase } from '../types'

export const threeByThreeVlsUlCases: AlgorithmCase[] = [
  { name: "VLS 164", image: "/algorithms/3x3/vls-ul/vls-ul-vls-164.svg", algorithm: "U2 F' U F U2 R U' R'" },
  { name: "VLS 165", image: "/algorithms/3x3/vls-ul/vls-ul-vls-165.svg", algorithm: "U R U R' U' F' L' U2 L U F" },
  { name: "VLS 166", image: "/algorithms/3x3/vls-ul/vls-ul-vls-166.svg", algorithm: "R' U' F R F' U' R' U2 R" },
  { name: "VLS 167", image: "/algorithms/3x3/vls-ul/vls-ul-vls-167.svg", algorithm: "R' U' F R F' R' U R" },
  { name: "VLS 168", image: "/algorithms/3x3/vls-ul/vls-ul-vls-168.svg", algorithm: "U R U R' U F' U' F U' R U' R'" },
  { name: "VLS 169", image: "/algorithms/3x3/vls-ul/vls-ul-vls-169.svg", algorithm: "R' U' F U R U' F'" },
  { name: "VLS 170", image: "/algorithms/3x3/vls-ul/vls-ul-vls-170.svg", algorithm: "R' F R F' U R U R' U' R' F R F'" },
  { name: "VLS 171", image: "/algorithms/3x3/vls-ul/vls-ul-vls-171.svg", algorithm: "y R U R' F R U' R' F2 U2 F" },
  { name: "VLS 172", image: "/algorithms/3x3/vls-ul/vls-ul-vls-172.svg", algorithm: "R' U' F U R F' U F U2 F'" },
  { name: "VLS 173", image: "/algorithms/3x3/vls-ul/vls-ul-vls-173.svg", algorithm: "U R' F R F' U F R' F' R" },
  { name: "VLS 174", image: "/algorithms/3x3/vls-ul/vls-ul-vls-174.svg", algorithm: "R2 U' R F R' U R2 U' F'" },
  { name: "VLS 175", image: "/algorithms/3x3/vls-ul/vls-ul-vls-175.svg", algorithm: "U2 R U' R' U R U' B U' B' R'" },
  { name: "VLS 176", image: "/algorithms/3x3/vls-ul/vls-ul-vls-176.svg", algorithm: "R' F R F' U F R U R' U' F'" },
  { name: "VLS 177", image: "/algorithms/3x3/vls-ul/vls-ul-vls-177.svg", algorithm: "U R U R' F2 r U r' F" },
  { name: "VLS 178", image: "/algorithms/3x3/vls-ul/vls-ul-vls-178.svg", algorithm: "U R B' U' R' U R B R'" },
  { name: "VLS 179", image: "/algorithms/3x3/vls-ul/vls-ul-vls-179.svg", algorithm: "y' R' U' R U' F R2 U R2 U' R2 F'" },
  { name: "VLS 180", image: "/algorithms/3x3/vls-ul/vls-ul-vls-180.svg", algorithm: "U2 R U' R' S' R U' R' S" },
  { name: "VLS 181", image: "/algorithms/3x3/vls-ul/vls-ul-vls-181.svg", algorithm: "U2 R U2 R' U R U R' U' R' F R F'" },
  { name: "VLS 182", image: "/algorithms/3x3/vls-ul/vls-ul-vls-182.svg", algorithm: "U F' U2 F R U' R'" },
  { name: "VLS 183", image: "/algorithms/3x3/vls-ul/vls-ul-vls-183.svg", algorithm: "U2 F' U F U' R U2 R'" },
  { name: "VLS 184", image: "/algorithms/3x3/vls-ul/vls-ul-vls-184.svg", algorithm: "U F' U r' F2 r U F" },
  { name: "VLS 185", image: "/algorithms/3x3/vls-ul/vls-ul-vls-185.svg", algorithm: "U R U R2 F R F' R U2 R'" },
  { name: "VLS 186", image: "/algorithms/3x3/vls-ul/vls-ul-vls-186.svg", algorithm: "U2 R U2 R2 F' U' F U R" },
  { name: "VLS 187", image: "/algorithms/3x3/vls-ul/vls-ul-vls-187.svg", algorithm: "U2 R' U' R U' R' U2 F R F'" },
  { name: "VLS 188", image: "/algorithms/3x3/vls-ul/vls-ul-vls-188.svg", algorithm: "U2 R U' R' U R' U' F' U F R2 U' R'" },
  { name: "VLS 189", image: "/algorithms/3x3/vls-ul/vls-ul-vls-189.svg", algorithm: "U2 x' R F' R U' R' U l' U R U2 R'" },
  { name: "VLS 190", image: "/algorithms/3x3/vls-ul/vls-ul-vls-190.svg", algorithm: "y' U R' U R U R2 F R F' R" },
]
