import type { AlgorithmCase } from '../types'

export const threeByThreeZbllPiCases: AlgorithmCase[] = [
  { name: "ZBLL Pi 1", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-1.svg", algorithm: "y' R U R' U R U2 R2 F' r U R U' r' F" },
  { name: "ZBLL Pi 2", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-2.svg", algorithm: "y' r' F' r U' r' F2 r2 U R' U' r' F R F'" },
  { name: "ZBLL Pi 3", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-3.svg", algorithm: "F R U' R' U R U R2 F' R U2 R U' R' U R U2 R' U'" },
  { name: "ZBLL Pi 4", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-4.svg", algorithm: "y2 R U R D R' U' R D' R U' R U' R' U2 R" },
  { name: "ZBLL Pi 5", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-5.svg", algorithm: "F R' F' R U2 R U2 R' U' r U R' U R U2 r'" },
  { name: "ZBLL Pi 6", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-6.svg", algorithm: "F R U R' U' R' F' R U2 R' U' R2 U' R2 U2 R" },
  { name: "ZBLL Pi 7", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-7.svg", algorithm: "R2 F R U R U' R' F' R U' R' U' R U R' U R" },
  { name: "ZBLL Pi 8", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-8.svg", algorithm: "y F U R U' R' U R U2 R' U' R U R' F'" },
  { name: "ZBLL Pi 9", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-9.svg", algorithm: "y' R U R' U R U' R' U' R' F' R U2 R U2 R' F" },
  { name: "ZBLL Pi 10", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-10.svg", algorithm: "y' F U' R U' R' U R U R' U2 R U2 R' U F'" },
  { name: "ZBLL Pi 11", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-11.svg", algorithm: "y' R F U R2 U2 R2 U R2 U R2 F' R'" },
  { name: "ZBLL Pi 12", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-12.svg", algorithm: "R' U' F' R U R' U' R' F R2 U2 R' U2 R" },
  { name: "ZBLL Pi 13", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-13.svg", algorithm: "y R2 D' R U2 R' D R2 U R2 D' R U R' D R2" },
  { name: "ZBLL Pi 14", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-14.svg", algorithm: "y' R2 D R' U2 R D' R2 U' R2 D R' U' R D' R2" },
  { name: "ZBLL Pi 15", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-15.svg", algorithm: "R' U' R U' R2 D' R U R' D R2 U' R' U2 R" },
  { name: "ZBLL Pi 16", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-16.svg", algorithm: "R U R' U R2 D R' U' R D' R2 U R U2 R'" },
  { name: "ZBLL Pi 17", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-17.svg", algorithm: "R' U' R U R2 F' R U R U' R' F U' R U R' U R" },
  { name: "ZBLL Pi 18", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-18.svg", algorithm: "y R U2 R' U' R U2 R' U2 R U' R2 D' R U' R' D R" },
  { name: "ZBLL Pi 19", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-19.svg", algorithm: "y' F U R U2 R' U R U R' F' R U2 R' U' R U' R'" },
  { name: "ZBLL Pi 20", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-20.svg", algorithm: "y2 R U2 R' U' R U' R' U' F U R U2 R' U R U R' F'" },
  { name: "ZBLL Pi 21", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-21.svg", algorithm: "y2 L' U R U' L U' R' U' R U' R'" },
  { name: "ZBLL Pi 22", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-22.svg", algorithm: "r' U r U r' U' r U R2 F R F' R" },
  { name: "ZBLL Pi 23", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-23.svg", algorithm: "r U' r' U' r U r' U' R2 B' R' B R' U" },
  { name: "ZBLL Pi 24", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-24.svg", algorithm: "y' R U R' U F' R U2 R' U2 R' F R" },
  { name: "ZBLL Pi 25", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-25.svg", algorithm: "R' U' R' D' R U' R' D R2 U R' U' R U R' U R" },
  { name: "ZBLL Pi 26", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-26.svg", algorithm: "R U' R' U' R U' R' U R U R' U R' F' R U R U' R' F" },
  { name: "ZBLL Pi 27", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-27.svg", algorithm: "y R U R' U R U' R' U R2 D R' U' R D' R' U' R'" },
  { name: "ZBLL Pi 28", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-28.svg", algorithm: "y2 R' U2 R U R' U' R U R2 F R U R U' R' F' R" },
  { name: "ZBLL Pi 29", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-29.svg", algorithm: "R U' L' U R' U' L U' R U' L' U R' U' L" },
  { name: "ZBLL Pi 30", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-30.svg", algorithm: "y F U R U' R' U R U' R2 F' R U R U' R'" },
  { name: "ZBLL Pi 31", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-31.svg", algorithm: "F U R U' R2 F' R2 U R' F' U' F U2 R U' R'" },
  { name: "ZBLL Pi 32", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-32.svg", algorithm: "y' R U R' U R U' R2 F R F' R U' R' F' U F" },
  { name: "ZBLL Pi 33", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-33.svg", algorithm: "y R' U' R U' B2 R' U2 R U2 l U2 l'" },
  { name: "ZBLL Pi 34", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-34.svg", algorithm: "y' R' U' R U' R' U R U' R' U R' D' R U R' D R2" },
  { name: "ZBLL Pi 35", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-35.svg", algorithm: "y2 R2 D R' U R D' R' U R' U' R U R' U' R U' R'" },
  { name: "ZBLL Pi 36", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-36.svg", algorithm: "R' U' R U' R' U2 R U' L' U R U' L U R'" },
  { name: "ZBLL Pi 37", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-37.svg", algorithm: "R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R" },
  { name: "ZBLL Pi 38", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-38.svg", algorithm: "R U R D R' U R D' R2 U' R U R' U' R U' R'" },
  { name: "ZBLL Pi 39", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-39.svg", algorithm: "y' R2 F2 R2 U' R U R' U R2 F2 R' U2 R'" },
  { name: "ZBLL Pi 40", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-40.svg", algorithm: "y' R' U' R U' R' U R U' R2 D' R U R' D R U R" },
  { name: "ZBLL Pi 41", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-41.svg", algorithm: "R U R' U' R' F R2 U R' U' R U R' U' F'" },
  { name: "ZBLL Pi 42", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-42.svg", algorithm: "y2 R U2 R' U2 R' F R2 U' R' U2 R U2 R' U' F'" },
  { name: "ZBLL Pi 43", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-43.svg", algorithm: "y R U2 R' U' R U R' U' R' D' R U' R' D R2 U' R' U R U' R'" },
  { name: "ZBLL Pi 44", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-44.svg", algorithm: "r' F' r U r U2 r' F2 U' R U R' U' R U' R'" },
  { name: "ZBLL Pi 45", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-45.svg", algorithm: "R U R' U R U2 R' U' R U' L' U R' U' L" },
  { name: "ZBLL Pi 46", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-46.svg", algorithm: "y' R' U2 R U R' U R2 U' r' F R' F' r" },
  { name: "ZBLL Pi 47", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-47.svg", algorithm: "y R U R' U R U' R' U R U' R D R' U' R D' R2" },
  { name: "ZBLL Pi 48", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-48.svg", algorithm: "y' R U R' U F2 R U2 R' U2 R' F2 R" },
  { name: "ZBLL Pi 49", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-49.svg", algorithm: "y R U2 R' U2 R' U' F U R2 U' R' U R U' R' F'" },
  { name: "ZBLL Pi 50", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-50.svg", algorithm: "y' R U R' F' R U R' U R U2 R' F U R U2 R'" },
  { name: "ZBLL Pi 51", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-51.svg", algorithm: "y2 R F U' R2 U2 R U R' U R2 U F' R'" },
  { name: "ZBLL Pi 52", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-52.svg", algorithm: "y R U R' U' R U R2 D' R U' R' D R U' R U2 R'" },
  { name: "ZBLL Pi 53", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-53.svg", algorithm: "F U R' U' R2 U' R2 U2 R U2 R U R' F'" },
  { name: "ZBLL Pi 54", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-54.svg", algorithm: "R U2 R2 F R F' R' F R F' R' F R F' R U2 R'" },
  { name: "ZBLL Pi 55", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-55.svg", algorithm: "R2 D R' U' R D' R' U' R' U R U' R' U' R U' R'" },
  { name: "ZBLL Pi 56", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-56.svg", algorithm: "R2 D' R U R' D R U R U' R' U R U R' U R" },
  { name: "ZBLL Pi 57", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-57.svg", algorithm: "y2 R U2 R' U R' D' R U R' D R2 U' R' U R U' R'" },
  { name: "ZBLL Pi 58", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-58.svg", algorithm: "R2 D R' U2 R D' R2 U' R U R D R' U2 R D' R2" },
  { name: "ZBLL Pi 59", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-59.svg", algorithm: "y' r U R' U R' F R F' R U' R' U R U2 r'" },
  { name: "ZBLL Pi 60", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-60.svg", algorithm: "y R U2 R' U' F' R U2 R' U' R U' R' F R U' R'" },
  { name: "ZBLL Pi 61", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-61.svg", algorithm: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: "ZBLL Pi 62", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-62.svg", algorithm: "y' R' U2 R U R' U R2 U R' U R U2 R'" },
  { name: "ZBLL Pi 63", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-63.svg", algorithm: "y' R U2 R' U2 R U' R' U2 R U' R' U2 R U R'" },
  { name: "ZBLL Pi 64", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-64.svg", algorithm: "y R' U2 R U2 R' U R U2 R' U R U2 R' U' R" },
  { name: "ZBLL Pi 65", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-65.svg", algorithm: "y2 R' U R U' R2 U2 R U R' U R2 U' R' U R" },
  { name: "ZBLL Pi 66", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-66.svg", algorithm: "y2 R U' R' U R2 U2 R' U' R U' R2 U R U' R'" },
  { name: "ZBLL Pi 67", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-67.svg", algorithm: "y R U2 R' U' R U' R2 U' R U' R' U2 R" },
  { name: "ZBLL Pi 68", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-68.svg", algorithm: "R' U2 R2 U R2 U R2 U2 R'" },
  { name: "ZBLL Pi 69", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-69.svg", algorithm: "R U R' U R U2 R' U' R U R' U R U2 R'" },
  { name: "ZBLL Pi 70", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-70.svg", algorithm: "R' U' R U' R' U2 R U R' U' R U' R' U2 R" },
  { name: "ZBLL Pi 71", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-71.svg", algorithm: "y R U R' U R U2 R' U R U R' U R U2 R'" },
  { name: "ZBLL Pi 72", image: "/algorithms/3x3/zbll-pi/zbll-pi-zbll-pi-72.svg", algorithm: "F R U R' U' R U R' U' F' R U R' U' M' U R U' r'" },
]
