export type CubingSiteCategory = 'algorithms' | 'brands' | 'community' | 'competitions' | 'shops' | 'solutions' | 'tools'

export type CubingSite = {
  category: CubingSiteCategory
  host: string
  id: string
  imagePath: string
  name: string
  url: string
}

export const cubingSites: readonly CubingSite[] = [
  {
    category: 'competitions',
    host: 'worldcubeassociation.org',
    id: 'world-cube-association',
    imagePath: '/sites/world-cube-association.png',
    name: 'World Cube Association',
    url: 'https://www.worldcubeassociation.org/',
  },
  {
    category: 'tools',
    host: 'cstimer.net',
    id: 'cstimer',
    imagePath: '/sites/cstimer.png',
    name: 'csTimer',
    url: 'https://cstimer.net/',
  },
  {
    category: 'solutions',
    host: 'jperm.net',
    id: 'j-perm',
    imagePath: '/sites/j-perm.png',
    name: 'J Perm',
    url: 'https://jperm.net/',
  },
  {
    category: 'community',
    host: 'speedsolving.com',
    id: 'speedsolving',
    imagePath: '/sites/speedsolving.png',
    name: 'Speedsolving Forum',
    url: 'https://www.speedsolving.com/',
  },
  {
    category: 'solutions',
    host: 'ruwix.com',
    id: 'ruwix',
    imagePath: '/sites/ruwix.png',
    name: 'Ruwix',
    url: 'https://ruwix.com/',
  },
  {
    category: 'tools',
    host: 'alg.cubing.net',
    id: 'alg-cubing',
    imagePath: '/sites/alg-cubing.png',
    name: 'alg.cubing.net',
    url: 'https://alg.cubing.net/',
  },
  {
    category: 'solutions',
    host: 'cubeskills.com',
    id: 'cubeskills',
    imagePath: '/sites/cubeskills.png',
    name: 'CubeSkills',
    url: 'https://www.cubeskills.com/',
  },
  {
    category: 'tools',
    host: 'cubedesk.io',
    id: 'cubedesk',
    imagePath: '/sites/cubedesk.png',
    name: 'CubeDesk',
    url: 'https://www.cubedesk.io/home',
  },
  {
    category: 'shops',
    host: 'thecubicle.com',
    id: 'the-cubicle',
    imagePath: '/sites/the-cubicle.png',
    name: 'The Cubicle',
    url: 'https://www.thecubicle.com/',
  },
  {
    category: 'shops',
    host: 'speedcubeshop.com',
    id: 'speedcubeshop',
    imagePath: '/sites/speedcubeshop.png',
    name: 'SpeedCubeShop',
    url: 'https://speedcubeshop.com/',
  },
  {
    category: 'shops',
    host: 'cubovelocidade.com.br',
    id: 'cubo-velocidade',
    imagePath: '/sites/cubo-velocidade.png',
    name: 'Cubo Velocidade',
    url: 'https://cubovelocidade.com.br/',
  },
  {
    category: 'algorithms',
    host: 'speedcubedb.com',
    id: 'speedcubedb',
    imagePath: '/sites/speedcubedb.png',
    name: 'SpeedCubeDB',
    url: 'https://speedcubedb.com/',
  },
  {
    category: 'tools',
    host: 'cubingapp.com',
    id: 'cubingapp',
    imagePath: '/sites/cubingapp.svg',
    name: 'CubingApp',
    url: 'https://cubingapp.com/',
  },
  {
    category: 'tools',
    host: 'cubing.net',
    id: 'cubing-net',
    imagePath: '/sites/cubing-net.png',
    name: 'Cubing.net',
    url: 'https://www.cubing.net/',
  },
  {
    category: 'tools',
    host: 'tnoodle.cubing.net',
    id: 'tnoodle',
    imagePath: '/sites/tnoodle.png',
    name: 'TNOODLE',
    url: 'https://tnoodle.cubing.net/',
  },
  {
    category: 'competitions',
    host: 'live.worldcubeassociation.org',
    id: 'wca-live',
    imagePath: '/sites/wca-live.png',
    name: 'WCA Live',
    url: 'https://live.worldcubeassociation.org/',
  },
  {
    category: 'competitions',
    host: 'cubingusa.org',
    id: 'cubingusa',
    imagePath: '/sites/cubingusa.png',
    name: 'CubingUSA',
    url: 'https://www.cubingusa.org/',
  },
  {
    category: 'community',
    host: 'reddit.com',
    id: 'reddit-cubers',
    imagePath: '/sites/reddit-cubers.png',
    name: 'Reddit r/Cubers',
    url: 'https://www.reddit.com/r/Cubers/',
  },
  {
    category: 'brands',
    host: 'rubiks.com',
    id: 'rubiks',
    imagePath: '/sites/rubiks.png',
    name: "Rubik's Official",
    url: 'https://www.rubiks.com/',
  },
  {
    category: 'brands',
    host: 'gancube.com',
    id: 'gan-cube',
    imagePath: '/sites/gan-cube.png',
    name: 'GAN Cube',
    url: 'https://www.gancube.com/',
  },
  {
    category: 'brands',
    host: 'moyustore.com',
    id: 'moyu',
    imagePath: '/sites/moyu.svg',
    name: 'MoYu',
    url: 'https://www.moyustore.com/',
  },
  {
    category: 'brands',
    host: 'qiyitoys.net',
    id: 'qiyi',
    imagePath: '/sites/qiyi.svg',
    name: 'QiYi',
    url: 'https://www.qiyitoys.net/',
  },
  {
    category: 'brands',
    host: 'yjcube.com',
    id: 'yj-cube',
    imagePath: '/sites/yj-cube.png',
    name: 'YJ Cube',
    url: 'https://www.yjcube.com/',
  },
  {
    category: 'shops',
    host: 'ziicube.com',
    id: 'ziicube',
    imagePath: '/sites/ziicube.png',
    name: 'Ziicube',
    url: 'https://www.ziicube.com/',
  },
  {
    category: 'shops',
    host: 'cubezz.com',
    id: 'cubezz',
    imagePath: '/sites/cubezz.png',
    name: 'Cubezz',
    url: 'https://www.cubezz.com/',
  },
  {
    category: 'shops',
    host: 'kewbz.co.uk',
    id: 'kewbzuk',
    imagePath: '/sites/kewbzuk.png',
    name: 'KewbzUK',
    url: 'https://kewbz.co.uk/',
  },
  {
    category: 'shops',
    host: 'dailypuzzles.com.au',
    id: 'dailypuzzles',
    imagePath: '/sites/dailypuzzles.png',
    name: 'DailyPuzzles',
    url: 'https://dailypuzzles.com.au/',
  },
  {
    category: 'community',
    host: 'speedcubereview.com',
    id: 'speedcubereview',
    imagePath: '/sites/speedcubereview.png',
    name: 'SpeedCubeReview',
    url: 'https://www.speedcubereview.com/',
  },
  {
    category: 'solutions',
    host: 'sarah.cubing.net',
    id: 'sarah-cubing',
    imagePath: '/sites/sarah-cubing.svg',
    name: "Sarah's Cubing Site",
    url: 'https://sarah.cubing.net/',
  },
  {
    category: 'solutions',
    host: 'jaapsch.net',
    id: 'jaaps-puzzle-page',
    imagePath: '/sites/jaaps-puzzle-page.png',
    name: "Jaap's Puzzle Page",
    url: 'https://www.jaapsch.net/puzzles/',
  },
  {
    category: 'solutions',
    host: 'ryanheise.com',
    id: 'ryan-heise',
    imagePath: '/sites/ryan-heise.png',
    name: 'Ryan Heise',
    url: 'https://www.ryanheise.com/cube/',
  },
  {
    category: 'solutions',
    host: 'lar5.com',
    id: 'lars-petrus',
    imagePath: '/sites/lars-petrus.png',
    name: 'Lars Petrus Method',
    url: 'https://lar5.com/cube/',
  },
  {
    category: 'solutions',
    host: 'speedsolving.com',
    id: 'speedsolving-wiki',
    imagePath: '/sites/speedsolving-wiki.png',
    name: 'Speedsolving Wiki',
    url: 'https://www.speedsolving.com/wiki/index.php/Main_Page',
  },
  {
    category: 'solutions',
    host: 'badmephisto.com',
    id: 'badmephisto',
    imagePath: '/sites/badmephisto.png',
    name: 'Badmephisto',
    url: 'http://badmephisto.com/',
  },
  {
    category: 'tools',
    host: 'ruwix.com',
    id: 'ruwix-solvers',
    imagePath: '/sites/ruwix-solvers.png',
    name: 'Ruwix Solvers',
    url: 'https://ruwix.com/cube-solver/',
  },
  {
    category: 'tools',
    host: 'grubiks.com',
    id: 'grubiks',
    imagePath: '/sites/grubiks.png',
    name: 'Grubiks',
    url: 'https://www.grubiks.com/solvers/rubiks-cube-3x3x3/',
  },
  {
    category: 'tools',
    host: 'cubesolve.com',
    id: 'cubesolve',
    imagePath: '/sites/cubesolve.png',
    name: 'CubeSolve',
    url: 'https://cubesolve.com/',
  },
  {
    category: 'algorithms',
    host: 'algdb.net',
    id: 'algdb',
    imagePath: '/sites/algdb.svg',
    name: 'AlgDb',
    url: 'https://algdb.net/',
  },
  {
    category: 'solutions',
    host: 'cubefreak.net',
    id: 'cubefreak',
    imagePath: '/sites/cubefreak.svg',
    name: 'Cubefreak',
    url: 'http://www.cubefreak.net/',
  },
]
