import type { AlgorithmCase } from '../types'

export const sixBySixL2cCases: AlgorithmCase[] = [
  { name: "Inner Center", image: "/algorithms/6x6/l2c/l2c-inner-center.svg", algorithm: "3L' U 3R U' 3L U 3R'" },
  { name: "Outer center", image: "/algorithms/6x6/l2c/l2c-outer-center.svg", algorithm: "U F Rw U' 3L' U Rw' U' 3L" },
  { name: "Front 3 Bar", image: "/algorithms/6x6/l2c/l2c-front-3-bar.svg", algorithm: "U Rw U 3R U Rw' U' 3R'" },
  { name: "Back 3 Bar", image: "/algorithms/6x6/l2c/l2c-back-3-bar.svg", algorithm: "U' Rw U' 3R U' Rw' U 3R'" },
  { name: "Pair and Split", image: "/algorithms/6x6/l2c/l2c-pair-and-split.svg", algorithm: "U' Rw U' Rw' U' 3R U Rw U' Rw' U Rw U' 3Rw'" },
  { name: "Pair And Split", image: "/algorithms/6x6/l2c/l2c-pair-and-split-2.svg", algorithm: "U Rw U Rw' U 3R U' Rw U Rw' U' Rw U 3Rw'" },
  { name: "Two Splits", image: "/algorithms/6x6/l2c/l2c-two-splits.svg", algorithm: "U Rw U Lw' 3R U Rw' U' Lw 3R'" },
  { name: "Two Pairs", image: "/algorithms/6x6/l2c/l2c-two-pairs.svg", algorithm: "U' Rw U 3Lw' U Rw' U' 3Lw" },
  { name: "Split and a Pair", image: "/algorithms/6x6/l2c/l2c-split-and-a-pair.svg", algorithm: "Rw U Rw' U2 Rw U' 3Lw' U Rw' U' 3Lw" },
  { name: "Split and a bar", image: "/algorithms/6x6/l2c/l2c-split-and-a-bar.svg", algorithm: "Rw U Rw' U2 Rw U 3R U' Rw' U 3R'" },
  { name: "Split and a bar", image: "/algorithms/6x6/l2c/l2c-split-and-a-bar-2.svg", algorithm: "Rw U' Rw' U2 Rw U' 3R U Rw' U' 3R'" },
  { name: "Pair and a Bar", image: "/algorithms/6x6/l2c/l2c-pair-and-a-bar.svg", algorithm: "U2 Rw U Rw' U2 Rw U' 3R U Rw' U' 3R'" },
  { name: "Pair and a Bar", image: "/algorithms/6x6/l2c/l2c-pair-and-a-bar-2.svg", algorithm: "U2 Rw U' Rw' U2 Rw U 3R U' Rw' U 3R'" },
  { name: "Split and a bad Bar", image: "/algorithms/6x6/l2c/l2c-split-and-a-bad-bar.svg", algorithm: "U' Rw U Rw' U Rw 3L' U' Rw' U 3L" },
  { name: "Split and a bad Bar", image: "/algorithms/6x6/l2c/l2c-split-and-a-bad-bar-2.svg", algorithm: "U Rw U' Rw' U' Rw 3L' U Rw' U' 3L" },
  { name: "Pair and a bad Bar", image: "/algorithms/6x6/l2c/l2c-pair-and-a-bad-bar.svg", algorithm: "U Rw U Rw' U 3Rw U' Rw' U 3R'" },
  { name: "Pair and a bad Bar", image: "/algorithms/6x6/l2c/l2c-pair-and-a-bad-bar-2.svg", algorithm: "U' Rw U' Rw' U' 3Rw U Rw' U' 3R'" },
  { name: "Stray Obliques", image: "/algorithms/6x6/l2c/l2c-stray-obliques.svg", algorithm: "3Rw U' Rw' U' Rw U2 3Rw' U Rw U Rw'" },
  { name: "Pair and a Nice 3 Ba", image: "/algorithms/6x6/l2c/l2c-pair-and-a-nice-3-ba.svg", algorithm: "3R U' Rw U 3Rw'" },
  { name: "L and a Bar", image: "/algorithms/6x6/l2c/l2c-l-and-a-bar.svg", algorithm: "3R U' Rw U 3Rw'" },
  { name: "L and a Bar", image: "/algorithms/6x6/l2c/l2c-l-and-a-bar-2.svg", algorithm: "U' 3Rw U Rw' U' 3R'" },
  { name: "Pair and a bad Bar", image: "/algorithms/6x6/l2c/l2c-pair-and-a-bad-bar-3.svg", algorithm: "U2 3Lw' U' Lw U 3L U Rw U Rw'" },
  { name: "Pair and a bad Bar", image: "/algorithms/6x6/l2c/l2c-pair-and-a-bad-bar-4.svg", algorithm: "U 3Lw' U Lw U' 3L U' Rw U' Rw'" },
  { name: "Bar and Scatter", image: "/algorithms/6x6/l2c/l2c-bar-and-scatter.svg", algorithm: "Rw' 3L F' Rw F 3L'" },
  { name: "Bar and Scatter", image: "/algorithms/6x6/l2c/l2c-bar-and-scatter-2.svg", algorithm: "U' 3L F Rw' F' 3L' Rw" },
  { name: "Front 3 Bar", image: "/algorithms/6x6/l2c/l2c-front-3-bar-2.svg", algorithm: "U' 3R U Rw U' Rw' U Rw U' 3Rw'" },
  { name: "Right 3 Bar", image: "/algorithms/6x6/l2c/l2c-right-3-bar.svg", algorithm: "3R U' Rw U Rw' U' Rw U 3Rw'" },
  { name: "Two Pairs", image: "/algorithms/6x6/l2c/l2c-two-pairs-2.svg", algorithm: "Rw U2 3Lw' U Rw' U' 3Lw" },
  { name: "Kite", image: "/algorithms/6x6/l2c/l2c-kite.svg", algorithm: "Rw U2 Rw' U Rw 3L' U' Rw' U 3L" },
  { name: "Triangle", image: "/algorithms/6x6/l2c/l2c-triangle.svg", algorithm: "U2 Rw U' Rw' U2 3Rw U Rw' U' 3R'" },
  { name: "Triangle", image: "/algorithms/6x6/l2c/l2c-triangle-2.svg", algorithm: "U Rw U Rw' U2 3Rw U' Rw' U 3R'" },
  { name: "Pair and Shape", image: "/algorithms/6x6/l2c/l2c-pair-and-shape.svg", algorithm: "U' Rw U2 Rw' U' 3R' F Rw' F' 3Rw" },
  { name: "Pair and Shape", image: "/algorithms/6x6/l2c/l2c-pair-and-shape-2.svg", algorithm: "Rw U2 Rw' U 3R' F' Rw' F 3Rw" },
]
