import type { AlgorithmCase } from '../../types'

export const fourByFourOllCases: AlgorithmCase[] = [
  { name: "H (FB)", image: "/algorithms/4x4/oll/4x4-oll-h-fb.png", algorithm: "[*] R2 D' R U2 R' D R U2 R" },
  { name: "H (LR)", image: "/algorithms/4x4/oll/4x4-oll-h-lr.png", algorithm: "[*] R U R' U R U' R' U R U2 R'" },
  { name: "Pi (B)", image: "/algorithms/4x4/oll/4x4-oll-pi-b.png", algorithm: "[*] U' 3Rw U R' U' 3Rw' F R F'" },
  { name: "Pi (F)", image: "/algorithms/4x4/oll/4x4-oll-pi-f.png", algorithm: "[*] U' R U2 R2 U' R2 U' R2 U2 R" },
  { name: "Pi (L)", image: "/algorithms/4x4/oll/4x4-oll-pi-l.png", algorithm: "[*] R' U2 R U R' U R" },
  { name: "Pi (R)", image: "/algorithms/4x4/oll/4x4-oll-pi-r.png", algorithm: "[*] U R' U' R U' R' U2 R" },
  { name: "Antisune (BL)", image: "/algorithms/4x4/oll/4x4-oll-antisune-bl.png", algorithm: "R' F R F' [*] R U' R'" },
  { name: "Antisune (BR)", image: "/algorithms/4x4/oll/4x4-oll-antisune-br.png", algorithm: "F R U R' U' F' [*]" },
  { name: "Antisune (FL)", image: "/algorithms/4x4/oll/4x4-oll-antisune-fl.png", algorithm: "[*] R U2 R2 U' R2 U' R2 U2 R" },
  { name: "Antisune (FR)", image: "/algorithms/4x4/oll/4x4-oll-antisune-fr.png", algorithm: "[*] U' R U2 R' U' R U' R'" },
  { name: "Sune (BL)", image: "/algorithms/4x4/oll/4x4-oll-sune-bl.png", algorithm: "F' L' U' L U F [*]" },
  { name: "Sune (BR)", image: "/algorithms/4x4/oll/4x4-oll-sune-br.png", algorithm: "L F' L' F [*] L' U L" },
  { name: "Sune (FL)", image: "/algorithms/4x4/oll/4x4-oll-sune-fl.png", algorithm: "[*] R U R' U R U2 R'" },
  { name: "Sune (FR)", image: "/algorithms/4x4/oll/4x4-oll-sune-fr.png", algorithm: "M' U R U' 3Rw' [*] U R U2 R'" },
  { name: "L (BL)", image: "/algorithms/4x4/oll/4x4-oll-l-bl.png", algorithm: "[*] R' U' R U' R' U2 R" },
  { name: "L (BR)", image: "/algorithms/4x4/oll/4x4-oll-l-br.png", algorithm: "[*] U R' U2 R U R' U R" },
  { name: "L (FL)", image: "/algorithms/4x4/oll/4x4-oll-l-fl.png", algorithm: "L U L' [*] L U' L'" },
  { name: "L (FR)", image: "/algorithms/4x4/oll/4x4-oll-l-fr.png", algorithm: "R' U' R [*] R' U R" },
  { name: "T (B)", image: "/algorithms/4x4/oll/4x4-oll-t-b.png", algorithm: "[*] U R U2 R2 U' R2 U' R2 U2 R" },
  { name: "T (F)", image: "/algorithms/4x4/oll/4x4-oll-t-f.png", algorithm: "R U R' U' R [*] R' U R U' R'" },
  { name: "T (L)", image: "/algorithms/4x4/oll/4x4-oll-t-l.png", algorithm: "F R U' R' U' R U R' F' [*]" },
  { name: "T (R)", image: "/algorithms/4x4/oll/4x4-oll-t-r.png", algorithm: "[*] R U R' U' R' F R F'" },
  { name: "U (B)", image: "/algorithms/4x4/oll/4x4-oll-u-b.png", algorithm: "M [*] M'" },
  { name: "U (F)", image: "/algorithms/4x4/oll/4x4-oll-u-f.png", algorithm: "[*]" },
  { name: "U (L)", image: "/algorithms/4x4/oll/4x4-oll-u-l.png", algorithm: "[*] R U2 R' U' R U' R'" },
  { name: "U (R)", image: "/algorithms/4x4/oll/4x4-oll-u-r.png", algorithm: "[*] U' R U R' U R U2 R'" },
  { name: "Solved", image: "/algorithms/4x4/oll/4x4-oll-solved.png", algorithm: "R U2 R' U' [*] F R' F' R" },
]
