import type { AlgorithmCase } from '../../types'

export const threeByThreeOllCases: AlgorithmCase[] = [
  { name: "29", image: "/algorithms/3x3/oll/oll-29.png", algorithm: "R U R' U' R U' R' F' U' F R U R'" },
  { name: "30", image: "/algorithms/3x3/oll/oll-30.png", algorithm: "F R' F R2 U' R' U' R U R' F2" },
  { name: "41", image: "/algorithms/3x3/oll/oll-41.png", algorithm: "R U R' U R U2 R' F R U R' U' F'" },
  { name: "42", image: "/algorithms/3x3/oll/oll-42.png", algorithm: "R' U' R U' R' U2 R F R U R' U' F'" },
  { name: "39", image: "/algorithms/3x3/oll/oll-39.png", algorithm: "L F' L' U' L U F U' L'" },
  { name: "40", image: "/algorithms/3x3/oll/oll-40.png", algorithm: "R' F R U R' U' F' U R" },
  { name: "34", image: "/algorithms/3x3/oll/oll-34.png", algorithm: "R U R2 U' R' F R U R U' F'" },
  { name: "46", image: "/algorithms/3x3/oll/oll-46.png", algorithm: "R' U' R' F R F' U R" },
  { name: "28", image: "/algorithms/3x3/oll/oll-28.png", algorithm: "r U R' U' r' R U R U' R'" },
  { name: "57", image: "/algorithms/3x3/oll/oll-57.png", algorithm: "R U R' U' M' U R U' r'" },
  { name: "21", image: "/algorithms/3x3/oll/oll-21.png", algorithm: "R U2 R' U' R U R' U' R U' R'" },
  { name: "22", image: "/algorithms/3x3/oll/oll-22.png", algorithm: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: "23", image: "/algorithms/3x3/oll/oll-23.png", algorithm: "R2 D' R U2 R' D R U2 R" },
  { name: "24", image: "/algorithms/3x3/oll/oll-24.png", algorithm: "r U R' U' r' F R F'" },
  { name: "25", image: "/algorithms/3x3/oll/oll-25.png", algorithm: "F' r U R' U' r' F R" },
  { name: "26", image: "/algorithms/3x3/oll/oll-26.png", algorithm: "R U2 R' U' R U' R'" },
  { name: "27", image: "/algorithms/3x3/oll/oll-27.png", algorithm: "R U R' U R U2 R'" },
  { name: "1", image: "/algorithms/3x3/oll/oll-1.png", algorithm: "R U2 R2 F R F' U2 R' F R F'" },
  { name: "2", image: "/algorithms/3x3/oll/oll-2.png", algorithm: "r U r' U2 r U2 R' U2 R U' r'" },
  { name: "3", image: "/algorithms/3x3/oll/oll-3.png", algorithm: "r' R2 U R' U r U2 r' U M'" },
  { name: "4", image: "/algorithms/3x3/oll/oll-4.png", algorithm: "M U' r U2 r' U' R U' R' M'" },
  { name: "17", image: "/algorithms/3x3/oll/oll-17.png", algorithm: "F R' F' R2 r' U R U' R' U' M'" },
  { name: "18", image: "/algorithms/3x3/oll/oll-18.png", algorithm: "r U R' U R U2 r2 U' R U' R' U2 r" },
  { name: "19", image: "/algorithms/3x3/oll/oll-19.png", algorithm: "r' R U R U R' U' M' R' F R F'" },
  { name: "20", image: "/algorithms/3x3/oll/oll-20.png", algorithm: "r U R' U' M2 U R U' R' U' M'" },
  { name: "9", image: "/algorithms/3x3/oll/oll-9.png", algorithm: "R U R' U' R' F R2 U R' U' F'" },
  { name: "10", image: "/algorithms/3x3/oll/oll-10.png", algorithm: "R U R' U R' F R F' R U2 R'" },
  { name: "35", image: "/algorithms/3x3/oll/oll-35.png", algorithm: "R U2 R2 F R F' R U2 R'" },
  { name: "37", image: "/algorithms/3x3/oll/oll-37.png", algorithm: "F R' F' R U R U' R'" },
  { name: "51", image: "/algorithms/3x3/oll/oll-51.png", algorithm: "F U R U' R' U R U' R' F'" },
  { name: "52", image: "/algorithms/3x3/oll/oll-52.png", algorithm: "R U R' U R U' B U' B' R'" },
  { name: "55", image: "/algorithms/3x3/oll/oll-55.png", algorithm: "R' F R U R U' R2 F' R2 U' R' U R U R'" },
  { name: "56", image: "/algorithms/3x3/oll/oll-56.png", algorithm: "r' U' r U' R' U R U' R' U R r' U r" },
  { name: "13", image: "/algorithms/3x3/oll/oll-13.png", algorithm: "F U R U' R2 F' R U R U' R'" },
  { name: "14", image: "/algorithms/3x3/oll/oll-14.png", algorithm: "R' F R U R' F' R F U' F'" },
  { name: "15", image: "/algorithms/3x3/oll/oll-15.png", algorithm: "l' U' l L' U' L U l' U l" },
  { name: "16", image: "/algorithms/3x3/oll/oll-16.png", algorithm: "r U r' R U R' U' r U' r'" },
  { name: "31", image: "/algorithms/3x3/oll/oll-31.png", algorithm: "R' U' F U R U' R' F' R" },
  { name: "32", image: "/algorithms/3x3/oll/oll-32.png", algorithm: "L U F' U' L' U L F L'" },
  { name: "43", image: "/algorithms/3x3/oll/oll-43.png", algorithm: "F' U' L' U L F" },
  { name: "44", image: "/algorithms/3x3/oll/oll-44.png", algorithm: "F U R U' R' F'" },
  { name: "47", image: "/algorithms/3x3/oll/oll-47.png", algorithm: "R' U' R' F R F' R' F R F' U R" },
  { name: "48", image: "/algorithms/3x3/oll/oll-48.png", algorithm: "F R U R' U' R U R' U' F'" },
  { name: "49", image: "/algorithms/3x3/oll/oll-49.png", algorithm: "r U' r2 U r2 U r2 U' r" },
  { name: "50", image: "/algorithms/3x3/oll/oll-50.png", algorithm: "r' U r2 U' r2 U' r2 U r'" },
  { name: "53", image: "/algorithms/3x3/oll/oll-53.png", algorithm: "l' U2 L U L' U' L U L' U l" },
  { name: "54", image: "/algorithms/3x3/oll/oll-54.png", algorithm: "r U2 R' U' R U R' U' R U' r'" },
  { name: "7", image: "/algorithms/3x3/oll/oll-7.png", algorithm: "r U R' U R U2 r'" },
  { name: "8", image: "/algorithms/3x3/oll/oll-8.png", algorithm: "l' U' L U' L' U2 l" },
  { name: "11", image: "/algorithms/3x3/oll/oll-11.png", algorithm: "r U R' U R' F R F' R U2 r'" },
  { name: "12", image: "/algorithms/3x3/oll/oll-12.png", algorithm: "M' R' U' R U' R' U2 R U' R r'" },
  { name: "5", image: "/algorithms/3x3/oll/oll-5.png", algorithm: "l' U2 L U L' U l" },
  { name: "6", image: "/algorithms/3x3/oll/oll-6.png", algorithm: "r U2 R' U' R U' r'" },
  { name: "33", image: "/algorithms/3x3/oll/oll-33.png", algorithm: "R U R' U' R' F R F'" },
  { name: "45", image: "/algorithms/3x3/oll/oll-45.png", algorithm: "F R U R' U' F'" },
  { name: "36", image: "/algorithms/3x3/oll/oll-36.png", algorithm: "L' U' L U' L' U L U L F' L' F" },
  { name: "38", image: "/algorithms/3x3/oll/oll-38.png", algorithm: "R U R' U R U' R' U' R' F R F'" },
]
