import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WCA Data OpenAPI skeleton', () => {
  it('documents status, data endpoints, errors, and attribution', async () => {
    const spec = await readFile(join(process.cwd(), 'openapi', 'wca-data-v1.yaml'), 'utf8')

    expect(spec).toContain('openapi: 3.0.3')
    expect(spec).toContain('title: Unofficial WCA Data API')
    expect(spec).toContain('not affiliated with, endorsed by, or operated by the World Cube Association')
    expect(spec).toContain('url: http://speedcube.com.br/api')
    expect(spec).toContain('x-tagGroups:')
    expect(spec).toContain('x-codeSamples:')
    expect(spec).toContain('production never falls back to fixture data')
    expect(spec).toContain('WCA sentinel values are preserved')
    expect(spec).toContain('/wca-data/v1/status:')
    expect(spec).toContain('/wca-data/v1/events:')
    expect(spec).toContain('/wca-data/v1/countries:')
    expect(spec).toContain('/wca-data/v1/continents:')
    expect(spec).toContain('/wca-data/v1/formats:')
    expect(spec).toContain('/wca-data/v1/round-types:')
    expect(spec).toContain('/wca-data/v1/championships:')
    expect(spec).toContain('/wca-data/v1/competitions:')
    expect(spec).toContain('/wca-data/v1/persons:')
    expect(spec).toContain('/wca-data/v1/rankings:')
    expect(spec).toContain('/wca-data/v1/results:')
    expect(spec).toContain('/wca-data/v1/scrambles:')
    expect(spec).toContain('/wca-data/v1/speedcubers/top:')
    expect(spec).toContain('/wca-data/v1/openapi.json:')
    expect(spec).toContain('/wca-data/v1/docs:')
    expect(spec).toContain('ListEnvelope:')
    expect(spec).toContain('StatusMetrics:')
    expect(spec).toContain('DatasetRecordCounts:')
    expect(spec).toContain('Continent:')
    expect(spec).toContain('Format:')
    expect(spec).toContain('RoundType:')
    expect(spec).toContain('Championship:')
    expect(spec).toContain('Competition:')
    expect(spec).toContain('Person:')
    expect(spec).toContain('RankEntry:')
    expect(spec).toContain('ResultEntry:')
    expect(spec).toContain('ScrambleEntry:')
    expect(spec).toContain('dataset_unavailable')
    expect(spec).toContain('World Cube Association Results Export')
  })
})
