import type { AlgorithmCase } from '../../types'

export const twoByTwoEgOneCases: AlgorithmCase[] = [
  { name: "AS1", image: "/algorithms/2x2/eg-1/2x2-eg-1-as1.png", algorithm: "R' F R2 U R' F' U' R U' R'" },
  { name: "AS2", image: "/algorithms/2x2/eg-1/2x2-eg-1-as2.png", algorithm: "R U' R' F' U' F2 R U' R'" },
  { name: "AS3", image: "/algorithms/2x2/eg-1/2x2-eg-1-as3.png", algorithm: "F L F' L2 U' L U F' L F L'" },
  { name: "AS4", image: "/algorithms/2x2/eg-1/2x2-eg-1-as4.png", algorithm: "F' R U R' U' R U R2 F' R" },
  { name: "AS5", image: "/algorithms/2x2/eg-1/2x2-eg-1-as5.png", algorithm: "R U' R2 F R U' R' F R F'" },
  { name: "AS6", image: "/algorithms/2x2/eg-1/2x2-eg-1-as6.png", algorithm: "L' U L U' L' U L U L F L' F'" },
  { name: "H1", image: "/algorithms/2x2/eg-1/2x2-eg-1-h1.png", algorithm: "R' F R2 U' R' F R U R' F'" },
  { name: "H2", image: "/algorithms/2x2/eg-1/2x2-eg-1-h2.png", algorithm: "F' U R U' R2 F2 R U' F" },
  { name: "H3", image: "/algorithms/2x2/eg-1/2x2-eg-1-h3.png", algorithm: "R U R' F' R U R' U' R U R'" },
  { name: "H4", image: "/algorithms/2x2/eg-1/2x2-eg-1-h4.png", algorithm: "R' F R F' U2 F R U2 R' F" },
  { name: "L1", image: "/algorithms/2x2/eg-1/2x2-eg-1-l1.png", algorithm: "R U' R' U R U' R2 F' R F" },
  { name: "L2", image: "/algorithms/2x2/eg-1/2x2-eg-1-l2.png", algorithm: "L' U L U' L' U L2 F L' F'" },
  { name: "L3", image: "/algorithms/2x2/eg-1/2x2-eg-1-l3.png", algorithm: "L' U' L F L' U' L U F' L F L'" },
  { name: "L4", image: "/algorithms/2x2/eg-1/2x2-eg-1-l4.png", algorithm: "R U R' F' R U R' U' F R' F' R" },
  { name: "L5", image: "/algorithms/2x2/eg-1/2x2-eg-1-l5.png", algorithm: "R' U R2 U' R2 U' F R2 U' R'" },
  { name: "L6", image: "/algorithms/2x2/eg-1/2x2-eg-1-l6.png", algorithm: "R' F R2 U R' F' R U2 R'" },
  { name: "Adjacent", image: "/algorithms/2x2/eg-1/2x2-eg-1-adjacent.png", algorithm: "R2 U' R2 U2 F2 U' R2" },
  { name: "Diagonal", image: "/algorithms/2x2/eg-1/2x2-eg-1-diagonal.png", algorithm: "R U' R' U' R' F2 U' R U R" },
  { name: "Solved", image: "/algorithms/2x2/eg-1/2x2-eg-1-solved.png", algorithm: "R' U R' U' R' F R2 U' R' U' R U R' F' R2" },
  { name: "P1", image: "/algorithms/2x2/eg-1/2x2-eg-1-p1.png", algorithm: "F U' R' F R U' F2 R U R'" },
  { name: "P2", image: "/algorithms/2x2/eg-1/2x2-eg-1-p2.png", algorithm: "R' F R2 U' R2 F R" },
  { name: "P3", image: "/algorithms/2x2/eg-1/2x2-eg-1-p3.png", algorithm: "F R' F U' F2 R U R" },
  { name: "P4", image: "/algorithms/2x2/eg-1/2x2-eg-1-p4.png", algorithm: "R U' R' U R U' R' F R U' R'" },
  { name: "P5", image: "/algorithms/2x2/eg-1/2x2-eg-1-p5.png", algorithm: "L F' L' F L F' L2 U' L U L' U L" },
  { name: "P6", image: "/algorithms/2x2/eg-1/2x2-eg-1-p6.png", algorithm: "R' F R F' R' F R2 U R' U' R U' R'" },
  { name: "S1", image: "/algorithms/2x2/eg-1/2x2-eg-1-s1.png", algorithm: "L F' L2 U' L F U L' U L" },
  { name: "S2", image: "/algorithms/2x2/eg-1/2x2-eg-1-s2.png", algorithm: "L' U L F U F2 L' U L" },
  { name: "S3", image: "/algorithms/2x2/eg-1/2x2-eg-1-s3.png", algorithm: "F' R' F R2 U R' U' F R' F' R" },
  { name: "S4", image: "/algorithms/2x2/eg-1/2x2-eg-1-s4.png", algorithm: "F L' U' L U L' U' L2 F L'" },
  { name: "S5", image: "/algorithms/2x2/eg-1/2x2-eg-1-s5.png", algorithm: "L' U L2 F' L' U L F' L' F" },
  { name: "S6", image: "/algorithms/2x2/eg-1/2x2-eg-1-s6.png", algorithm: "R U' R' U R U' R' U' R' F' R F" },
  { name: "T1", image: "/algorithms/2x2/eg-1/2x2-eg-1-t1.png", algorithm: "R2 B2 U' R' U' R U' R' U R'" },
  { name: "T2", image: "/algorithms/2x2/eg-1/2x2-eg-1-t2.png", algorithm: "L' U L2 F' L' U' L' U2 L" },
  { name: "T3", image: "/algorithms/2x2/eg-1/2x2-eg-1-t3.png", algorithm: "R' F' R2 U R' F' R U R'" },
  { name: "T4", image: "/algorithms/2x2/eg-1/2x2-eg-1-t4.png", algorithm: "R U R' F R U R' F U' R U' R'" },
  { name: "T5", image: "/algorithms/2x2/eg-1/2x2-eg-1-t5.png", algorithm: "F L F' L2 U' L U L' U' L" },
  { name: "T6", image: "/algorithms/2x2/eg-1/2x2-eg-1-t6.png", algorithm: "F' R' F R2 U R' U' R U R'" },
  { name: "U1", image: "/algorithms/2x2/eg-1/2x2-eg-1-u1.png", algorithm: "F R U' R' F x F' L' U' L' U x'" },
  { name: "U2", image: "/algorithms/2x2/eg-1/2x2-eg-1-u2.png", algorithm: "R U' R2 F R2 U R' U' R U' R'" },
  { name: "U3", image: "/algorithms/2x2/eg-1/2x2-eg-1-u3.png", algorithm: "L F' L' F L F' L2 U L" },
  { name: "U4", image: "/algorithms/2x2/eg-1/2x2-eg-1-u4.png", algorithm: "F' U2 R U2 R' U2 F" },
  { name: "U5", image: "/algorithms/2x2/eg-1/2x2-eg-1-u5.png", algorithm: "F' U L F2 L' F U2 F" },
  { name: "U6", image: "/algorithms/2x2/eg-1/2x2-eg-1-u6.png", algorithm: "F U' R' F2 R F' U2 F'" },
]
