import type { AlgorithmCase } from '../../types'

export const threeByThreeZbllLCases: AlgorithmCase[] = [
  { name: "ZBLL L 1", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-1.svg", algorithm: "y' R' U' R U' R' U2 R' D' R U2 R' D R U2 R" },
  { name: "ZBLL L 2", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-2.svg", algorithm: "y R D R' U2 R D' R' U' R' U2 R U' R' U' R" },
  { name: "ZBLL L 3", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-3.svg", algorithm: "y' R' U2 R U R2 D' R U R' D R2" },
  { name: "ZBLL L 4", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-4.svg", algorithm: "R' U2 R' D' r U2 r' D R2" },
  { name: "ZBLL L 5", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-5.svg", algorithm: "R' U2 R U2 R' U' R2 D R' U2 R D' R2 U2 R" },
  { name: "ZBLL L 6", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-6.svg", algorithm: "R' U2 R' D' R U2 R' D R2" },
  { name: "ZBLL L 7", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-7.svg", algorithm: "y' R' U' R U' R' U' R U2 R D r' U2 r D' R'" },
  { name: "ZBLL L 8", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-8.svg", algorithm: "y' F R U' R' U R U R2 D' R U R' D R2 U' R' F'" },
  { name: "ZBLL L 9", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-9.svg", algorithm: "y' R' U' R2 D r' U2 r D' R2 U R U R' U2 R" },
  { name: "ZBLL L 10", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-10.svg", algorithm: "R' U R U' R' U F' R U2 R' U2 R' F R2" },
  { name: "ZBLL L 11", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-11.svg", algorithm: "R' U R2 D R' U R D' R' U2 R' U R U R' U' R" },
  { name: "ZBLL L 12", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-12.svg", algorithm: "y' F R U' R' U' R2 D R' U R D' R' U R' U' F'" },
  { name: "ZBLL L 13", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-13.svg", algorithm: "R2 D' R U2 R' D R2 U R2 F' R U R U' R' F R" },
  { name: "ZBLL L 14", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-14.svg", algorithm: "y R U' R' U R U' R' U' R U R2 D' R U' R' D R" },
  { name: "ZBLL L 15", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-15.svg", algorithm: "L U' R U R' L' U2 R U' R' U' R U' R'" },
  { name: "ZBLL L 16", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-16.svg", algorithm: "R' U2 R2 U R' U' R' U2 F R U R U' R' F'" },
  { name: "ZBLL L 17", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-17.svg", algorithm: "R' U' R U' R' U R U' R' U R U' R2 D' R U2 R' D R2" },
  { name: "ZBLL L 18", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-18.svg", algorithm: "y F R' F' r U R U' r'" },
  { name: "ZBLL L 19", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-19.svg", algorithm: "y' R' U2 R U2 D' R U' R U R U' R2 D" },
  { name: "ZBLL L 20", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-20.svg", algorithm: "L R U' R' U L' R U R' U R U' R'" },
  { name: "ZBLL L 21", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-21.svg", algorithm: "y R U R D R' U2 R D' R' U' R' U R U R'" },
  { name: "ZBLL L 22", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-22.svg", algorithm: "R U R' U R U' R' U' L' U R U' R' L" },
  { name: "ZBLL L 23", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-23.svg", algorithm: "y F R U R' U' R' F' R U2 R U2 R'" },
  { name: "ZBLL L 24", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-24.svg", algorithm: "y' R' F' R U R' U' R' F R U' R U R' U R" },
  { name: "ZBLL L 25", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-25.svg", algorithm: "y' R2 D' r U2 r' R U R' D R U R" },
  { name: "ZBLL L 26", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-26.svg", algorithm: "y' R' U R U2 R' L' U R U L U r' F r" },
  { name: "ZBLL L 27", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-27.svg", algorithm: "R' D R' U R D' R' U R2 U' R2 U' R2" },
  { name: "ZBLL L 28", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-28.svg", algorithm: "y2 F' R U2 R' U2 R' F U2 R U R U' R2 U2 R" },
  { name: "ZBLL L 29", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-29.svg", algorithm: "y2 F' r U R' U' r' F R" },
  { name: "ZBLL L 30", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-30.svg", algorithm: "y R U R' U R U' R' U R U' R' U R2 D R' U2 R D' R2" },
  { name: "ZBLL L 31", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-31.svg", algorithm: "y' R' F R U R U' R' F' U R U R' U R U' R'" },
  { name: "ZBLL L 32", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-32.svg", algorithm: "y R' U' R U2 R' F' R U R' U' R' F R2 U R' U2 R" },
  { name: "ZBLL L 33", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-33.svg", algorithm: "y2 F' R U2 R' U2 R' F R U R U' R'" },
  { name: "ZBLL L 34", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-34.svg", algorithm: "y R U R' U R' D' R U2 R' D R2 U' R' U R U' R'" },
  { name: "ZBLL L 35", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-35.svg", algorithm: "R' U' R' D' R U2 R' D R U R U' R' U' R" },
  { name: "ZBLL L 36", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-36.svg", algorithm: "y' F R U' R' U' R U2 R' U' F'" },
  { name: "ZBLL L 37", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-37.svg", algorithm: "y2 R U R' U R U2 R D R' U2 R D' R' U2 R'" },
  { name: "ZBLL L 38", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-38.svg", algorithm: "y2 R U2 R' U' R2 D R' U' R D' R2" },
  { name: "ZBLL L 39", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-39.svg", algorithm: "R' D' R U2 R' D R U R U2 R' U R U R'" },
  { name: "ZBLL L 40", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-40.svg", algorithm: "R' F' R U R' U' R' F R2 U' R' U2 R" },
  { name: "ZBLL L 41", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-41.svg", algorithm: "y R U2 R D R' U2 R D' R2" },
  { name: "ZBLL L 42", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-42.svg", algorithm: "y R U2 R' U2 R U R2 D' R U2 R' D R2 U2 R'" },
  { name: "ZBLL L 43", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-43.svg", algorithm: "y2 F R U R' U' R' F' U' R U R U' R' U' R' U R" },
  { name: "ZBLL L 44", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-44.svg", algorithm: "y2 R U R' U R U R' U2 R' D' r U2 r' D R" },
  { name: "ZBLL L 45", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-45.svg", algorithm: "y R U' R2 D' R U' R' D R U2 R U' R' U' R U R'" },
  { name: "ZBLL L 46", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-46.svg", algorithm: "y2 R' F' R U2 R U2 R' F U' R U R' U' R U' R'" },
  { name: "ZBLL L 47", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-47.svg", algorithm: "y R' U R U2 R' U' R U2 R' U' R U' R2 D' R U R' D R2" },
  { name: "ZBLL L 48", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-48.svg", algorithm: "y' R' F' R U R' U' R' F D' R U' R' D R2 U R' U R" },
  { name: "ZBLL L 49", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-49.svg", algorithm: "y r U2 r2 F R F' r2 R' U2 r'" },
  { name: "ZBLL L 50", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-50.svg", algorithm: "y R U' R' U R U' R' U' R U R' U2 R' D' R U R' D R" },
  { name: "ZBLL L 51", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-51.svg", algorithm: "R' U R U' R' U R U R' U' R U2 R D R' U' R D' R'" },
  { name: "ZBLL L 52", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-52.svg", algorithm: "r U2 R r2 F R' F' r2 U2 r'" },
  { name: "ZBLL L 53", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-53.svg", algorithm: "y2 F' r U R' U R' D R U' R' D' R U' r' F R" },
  { name: "ZBLL L 54", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-54.svg", algorithm: "r U R2 D' R U2 R' D R U r' F R F'" },
  { name: "ZBLL L 55", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-55.svg", algorithm: "y R' U R U' R' U' R U' R' U2 R' D' R U' R' D R2" },
  { name: "ZBLL L 56", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-56.svg", algorithm: "y2 B' R U R' U' R' F R2 U' R' U' R U R' S z'" },
  { name: "ZBLL L 57", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-57.svg", algorithm: "y' R' U' R U R' F' R U R' U' R' F R2" },
  { name: "ZBLL L 58", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-58.svg", algorithm: "y F R U R2 F R F' R U' R' F'" },
  { name: "ZBLL L 59", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-59.svg", algorithm: "y' L' U2 R U' R' U2 L R U' R'" },
  { name: "ZBLL L 60", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-60.svg", algorithm: "y2 R U R' U F' R U2 R' U' R' U' R' F R U R" },
  { name: "ZBLL L 61", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-61.svg", algorithm: "y' R2 U R' U R' U' R U' R' U' R U R U' R2" },
  { name: "ZBLL L 62", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-62.svg", algorithm: "y R U2 R' U' R U' R' U R' U2 R U R' U R" },
  { name: "ZBLL L 63", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-63.svg", algorithm: "y R U R' U R U2 R' U R' U' R U' R' U2 R" },
  { name: "ZBLL L 64", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-64.svg", algorithm: "y R2 U' R U R U' R' U' R U' R' U R' U R2" },
  { name: "ZBLL L 65", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-65.svg", algorithm: "R' U2 R U R' U R U' R U2 R' U' R U' R'" },
  { name: "ZBLL L 66", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-66.svg", algorithm: "y2 R2 U' R U' R U R' U R U R' U' R' U R2" },
  { name: "ZBLL L 67", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-67.svg", algorithm: "R' U' R U' R' U2 R U' R U R' U R U2 R'" },
  { name: "ZBLL L 68", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-68.svg", algorithm: "R2 U R' U' R' U R U R' U R U' R U' R2" },
  { name: "ZBLL L 69", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-69.svg", algorithm: "y R U2 R' U' R U' R' U2 R U R' U R U2 R'" },
  { name: "ZBLL L 70", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-70.svg", algorithm: "y R U R' U R U2 R' U2 R U2 R' U' R U' R'" },
  { name: "ZBLL L 71", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-71.svg", algorithm: "y' R U R' U R U' R' U R U' R' U R U2 R'" },
  { name: "ZBLL L 72", image: "/algorithms/3x3/zbll-l/zbll-l-zbll-l-72.svg", algorithm: "R U R' U R U' R' U R U2 R' U' R U2 R' U' R U' R'" },
]
