import type { AlgorithmCase } from '../types'

export const megaminxOllCases: AlgorithmCase[] = [
  { name: "1A", image: "/algorithms/megaminx/oll/oll-1a.png", algorithm: "L R U R' U' R' F R F' L'" },
  { name: "1B", image: "/algorithms/megaminx/oll/oll-1b.png", algorithm: "L F R' F' R U R U' R' L'" },
  { name: "2A", image: "/algorithms/megaminx/oll/oll-2a.png", algorithm: "R U R' U R U R' U2' R U' R'" },
  { name: "2B", image: "/algorithms/megaminx/oll/oll-2b.png", algorithm: "R BR R' F R BR' R' F'" },
  { name: "2C", image: "/algorithms/megaminx/oll/oll-2c.png", algorithm: "R' U2 R U R' U2 R" },
  { name: "2D", image: "/algorithms/megaminx/oll/oll-2d.png", algorithm: "R' F R BR' R' F' R BR" },
  { name: "3A-", image: "/algorithms/megaminx/oll/oll-3a.png", algorithm: "R' U' R U' R' U2 R" },
  { name: "3A+", image: "/algorithms/megaminx/oll/oll-3a-2.png", algorithm: "R U R' U R U2' R'" },
  { name: "3B-", image: "/algorithms/megaminx/oll/oll-3b.png", algorithm: "R' U2' R U R' U R" },
  { name: "3B+", image: "/algorithms/megaminx/oll/oll-3b-2.png", algorithm: "R U2 R' U' R U' R'" },
  { name: "4A", image: "/algorithms/megaminx/oll/oll-4a.png", algorithm: "R U R' U R U' R' U R U2' R'" },
  { name: "4B", image: "/algorithms/megaminx/oll/oll-4b.png", algorithm: "y2' R U2 R' U' R U R' U' R U' R'" },
  { name: "4C", image: "/algorithms/megaminx/oll/oll-4c.png", algorithm: "R U R' U R U R' U' R U2' R'" },
  { name: "4D", image: "/algorithms/megaminx/oll/oll-4d.png", algorithm: "R U2' R' U2' R U2 R' U2' R U' R'" },
  { name: "4E-", image: "/algorithms/megaminx/oll/oll-4e.png", algorithm: "R' U2' R2 U R2' U R2 U2' R'" },
  { name: "4E+", image: "/algorithms/megaminx/oll/oll-4e-2.png", algorithm: "R U2 R2' U' R2 U' R2' U2 R" },
  { name: "5-", image: "/algorithms/megaminx/oll/oll-5.png", algorithm: "R U2 R' U' R U2 R' U2' R U' R'" },
  { name: "5+", image: "/algorithms/megaminx/oll/oll-5-2.png", algorithm: "R U R' U2 R U2' R' U R U2' R'" },
  { name: "6A", image: "/algorithms/megaminx/oll/oll-6a.png", algorithm: "R U2' R' F R' F' R U' R U2' R'" },
  { name: "6B", image: "/algorithms/megaminx/oll/oll-6b.png", algorithm: "F R U' R' U2 R U R' F'" },
  { name: "7A", image: "/algorithms/megaminx/oll/oll-7a.png", algorithm: "R U R' U' R' F R F'" },
  { name: "7B", image: "/algorithms/megaminx/oll/oll-7b.png", algorithm: "F R U R' U' F'" },
  { name: "8A-", image: "/algorithms/megaminx/oll/oll-8a.png", algorithm: "y2' R U R BR' R' BR U' R'" },
  { name: "8A+", image: "/algorithms/megaminx/oll/oll-8a-2.png", algorithm: "R' U' R' F R F' U R" },
  { name: "8B-", image: "/algorithms/megaminx/oll/oll-8b.png", algorithm: "F R U R' U' R U R' U R U2' R' F'" },
  { name: "8B+", image: "/algorithms/megaminx/oll/oll-8b-2.png", algorithm: "R U R2' U' R' F R U R U' F'" },
  { name: "9A-", image: "/algorithms/megaminx/oll/oll-9a.png", algorithm: "R U R' F' U' F U R U2' R'" },
  { name: "9A+", image: "/algorithms/megaminx/oll/oll-9a-2.png", algorithm: "R' F R U R' U' F' U R" },
  { name: "9B-", image: "/algorithms/megaminx/oll/oll-9b.png", algorithm: "F U R U R' U2' F'" },
  { name: "9B+", image: "/algorithms/megaminx/oll/oll-9b-2.png", algorithm: "R' U' F' U' F U2 R" },
  { name: "10A-", image: "/algorithms/megaminx/oll/oll-10a.png", algorithm: "R' F' U' F U2' R U R' U2 R" },
  { name: "10A+", image: "/algorithms/megaminx/oll/oll-10a-2.png", algorithm: "R U R' U2 R U' R' U2' R' F R F" },
  { name: "10B-", image: "/algorithms/megaminx/oll/oll-10b.png", algorithm: "R U2 R' U R' F R F' R U2 R'" },
  { name: "10B+", image: "/algorithms/megaminx/oll/oll-10b-2.png", algorithm: "R U' R' U2' R' F R F' U2 R U R'" },
  { name: "11A-", image: "/algorithms/megaminx/oll/oll-11a.png", algorithm: "R U2 R' U R' F' U' F U R2 U2 R'" },
  { name: "11A+", image: "/algorithms/megaminx/oll/oll-11a-2.png", algorithm: "R' U' F' U' F R2 U R2' U R2 U2' R'" },
  { name: "11B-", image: "/algorithms/megaminx/oll/oll-11b.png", algorithm: "R U2' R' U' R' F R F' U R U2 R'" },
  { name: "11B+", image: "/algorithms/megaminx/oll/oll-11b-2.png", algorithm: "R' U2' R' F R F' R U R' U R" },
  { name: "12-", image: "/algorithms/megaminx/oll/oll-12.png", algorithm: "R' U2' R U' R' U F' U F U R" },
  { name: "12+", image: "/algorithms/megaminx/oll/oll-12-2.png", algorithm: "F R U' R' U2 R U R' U R U' R' F'" },
  { name: "13-", image: "/algorithms/megaminx/oll/oll-13.png", algorithm: "F R' F' U2' F R F' R' U2 R" },
  { name: "13+", image: "/algorithms/megaminx/oll/oll-13-2.png", algorithm: "R' F R U2 R' F' R F U2' F'" },
  { name: "14A-", image: "/algorithms/megaminx/oll/oll-14a.png", algorithm: "BR' R' U2' R U2 BR" },
  { name: "14A+", image: "/algorithms/megaminx/oll/oll-14a-2.png", algorithm: "F R U2 R' U2' F'" },
  { name: "14B-", image: "/algorithms/megaminx/oll/oll-14b.png", algorithm: "R' F' U' F R U2' R' U2' R" },
  { name: "14B+", image: "/algorithms/megaminx/oll/oll-14b-2.png", algorithm: "R' U2 R U2 R' F' U F R" },
  { name: "15A-", image: "/algorithms/megaminx/oll/oll-15a.png", algorithm: "F R' F' U' F R F' R' U R" },
  { name: "15A+", image: "/algorithms/megaminx/oll/oll-15a-2.png", algorithm: "R' F R U R' F' R F U' F'" },
  { name: "15B-", image: "/algorithms/megaminx/oll/oll-15b.png", algorithm: "F R' F' U' F R F' R' U' R U R' U R" },
  { name: "15B+", image: "/algorithms/megaminx/oll/oll-15b-2.png", algorithm: "L' F U R U R' U2' F' L" },
  { name: "16A-", image: "/algorithms/megaminx/oll/oll-16a.png", algorithm: "R' U2' R' F R F' R U' R' U2' R" },
  { name: "16A+", image: "/algorithms/megaminx/oll/oll-16a-2.png", algorithm: "R' F R2 U R' U R U2' R2' F' R" },
  { name: "16B-", image: "/algorithms/megaminx/oll/oll-16b.png", algorithm: "R' U' R U' R' F U R U' R' F' U2 R" },
  { name: "16B+", image: "/algorithms/megaminx/oll/oll-16b-2.png", algorithm: "F R U2 R' U' F R' F' R U' F'" },
  { name: "17A-", image: "/algorithms/megaminx/oll/oll-17a.png", algorithm: "R U2 R BR' R' BR U2" },
  { name: "17A+", image: "/algorithms/megaminx/oll/oll-17a-2.png", algorithm: "R' U2' R' F R F' U2 R" },
  { name: "17B-", image: "/algorithms/megaminx/oll/oll-17b.png", algorithm: "L F R U R' U' F' L'" },
  { name: "17B+", image: "/algorithms/megaminx/oll/oll-17b-2.png", algorithm: "BL' F R U R' U' F' BL" },
  { name: "18A", image: "/algorithms/megaminx/oll/oll-18a.png", algorithm: "R' F U R U' R2' F' R2 U R' U' R" },
  { name: "18B", image: "/algorithms/megaminx/oll/oll-18b.png", algorithm: "R' F' U' F U R2 U2 R' U R U2 R'" },
  { name: "18C", image: "/algorithms/megaminx/oll/oll-18c.png", algorithm: "F U R U' R' U R U' R' F'" },
  { name: "18D", image: "/algorithms/megaminx/oll/oll-18d.png", algorithm: "R' U2' R U R' F R' F' R U R" },
  { name: "18E-", image: "/algorithms/megaminx/oll/oll-18e.png", algorithm: "R' F' U' F U' R U R' U R" },
  { name: "18E+", image: "/algorithms/megaminx/oll/oll-18e-2.png", algorithm: "R' F' U2' F R U R' U R" },
  { name: "19A-", image: "/algorithms/megaminx/oll/oll-19a.png", algorithm: "F U2 R U' R' U' R U R' U' F'" },
  { name: "19A+", image: "/algorithms/megaminx/oll/oll-19a-2.png", algorithm: "F U R U' R' U R U R' U2' F'" },
  { name: "19B-", image: "/algorithms/megaminx/oll/oll-19b.png", algorithm: "R' U2' R U R' F' U' F R U R' U R" },
  { name: "19B+", image: "/algorithms/megaminx/oll/oll-19b-2.png", algorithm: "R U2' R' F' U' F U' R U' R'" },
  { name: "19C-", image: "/algorithms/megaminx/oll/oll-19c.png", algorithm: "R U2' R' F R' F' R U2' R U' R'" },
  { name: "19C+", image: "/algorithms/megaminx/oll/oll-19c-2.png", algorithm: "F R U' R' U R U2' R' U2' R U R' U' F'" },
  { name: "19D-", image: "/algorithms/megaminx/oll/oll-19d.png", algorithm: "BR' U' R' U' R U R' U' R U2 BR" },
  { name: "19D+", image: "/algorithms/megaminx/oll/oll-19d-2.png", algorithm: "F U R U R' U' R U R' U2' F'" },
  { name: "19E-", image: "/algorithms/megaminx/oll/oll-19e.png", algorithm: "R' U' R' F R2 U' R' U2 R U R' F' R" },
  { name: "19E+", image: "/algorithms/megaminx/oll/oll-19e-2.png", algorithm: "R U R' U R U' R' U R U' R' U' R' F R F'" },
  { name: "19F-", image: "/algorithms/megaminx/oll/oll-19f.png", algorithm: "R' U2' R2 U R2' U R U2' R' F R F'" },
  { name: "19F+", image: "/algorithms/megaminx/oll/oll-19f-2.png", algorithm: "R U2' R' U2' R U R' U2' R' F R F'" },
  { name: "20A-", image: "/algorithms/megaminx/oll/oll-20a.png", algorithm: "F R U2 R' U2' R U R' U' F'" },
  { name: "20A+", image: "/algorithms/megaminx/oll/oll-20a-2.png", algorithm: "BR' R' U2' R U2 R' U' R U BR" },
  { name: "20B-", image: "/algorithms/megaminx/oll/oll-20b.png", algorithm: "R' F' U' F U R2 U2 R' U' R U' R'" },
  { name: "20B+", image: "/algorithms/megaminx/oll/oll-20b-2.png", algorithm: "R' F' U' F U R U2' R' U2' R U R' U R" },
  { name: "20C-", image: "/algorithms/megaminx/oll/oll-20c.png", algorithm: "F U2 R U' R' U R U' R' U' F'" },
  { name: "20C+", image: "/algorithms/megaminx/oll/oll-20c-2.png", algorithm: "BR' U2' R' U R U' R' U R U BR" },
  { name: "20D-", image: "/algorithms/megaminx/oll/oll-20d.png", algorithm: "F R U' R' U R U2' R' U' R U' R' F'" },
  { name: "20D+", image: "/algorithms/megaminx/oll/oll-20d-2.png", algorithm: "R' F R' F' R2 U' R' F' U' F R" },
  { name: "20E-", image: "/algorithms/megaminx/oll/oll-20e.png", algorithm: "R' U2' R F U R' U R2 U2' R' F'" },
  { name: "20E+", image: "/algorithms/megaminx/oll/oll-20e-2.png", algorithm: "F R U R' U' R U2 R' U' R U' R' F'" },
  { name: "20F-", image: "/algorithms/megaminx/oll/oll-20f.png", algorithm: "R' U' R F U' R' U2 R U2 R U' R' F'" },
  { name: "20F+", image: "/algorithms/megaminx/oll/oll-20f-2.png", algorithm: "R U2' R' U' R U' R' U' R' F R F'" },
  { name: "21A-", image: "/algorithms/megaminx/oll/oll-21a.png", algorithm: "BR' U2' R' U2 R U' R' U R BR" },
  { name: "21A+", image: "/algorithms/megaminx/oll/oll-21a-2.png", algorithm: "F U2 R U2' R' U R U' R' F'" },
  { name: "21B-", image: "/algorithms/megaminx/oll/oll-21b.png", algorithm: "R' F' U' F R U2' R' U2 R U' R' U2 R" },
  { name: "21B+", image: "/algorithms/megaminx/oll/oll-21b-2.png", algorithm: "R' U2' F' U F U' R U R' U R" },
  { name: "21C-", image: "/algorithms/megaminx/oll/oll-21c.png", algorithm: "BR' U' R' U R U2' R' U2 R U' R' U R BR" },
  { name: "21C+", image: "/algorithms/megaminx/oll/oll-21c-2.png", algorithm: "R' F' U2' F2 R U R' U' F' U2 R" },
  { name: "21D-", image: "/algorithms/megaminx/oll/oll-21d.png", algorithm: "BR' U2' R' U2 R U2' R' U2 R BR" },
  { name: "21D+", image: "/algorithms/megaminx/oll/oll-21d-2.png", algorithm: "R' F' U' F U2' R U2 R' U R" },
  { name: "21E-", image: "/algorithms/megaminx/oll/oll-21e.png", algorithm: "F R U R' U' R U2 R' U2' F'" },
  { name: "21E+", image: "/algorithms/megaminx/oll/oll-21e-2.png", algorithm: "BR' R' U' R U R' U2' R U2 BR" },
  { name: "22A", image: "/algorithms/megaminx/oll/oll-22a.png", algorithm: "R U2 R2' F R F' R U2' R'" },
  { name: "22B", image: "/algorithms/megaminx/oll/oll-22b.png", algorithm: "F R' F' R U R U' R'" },
  { name: "23A", image: "/algorithms/megaminx/oll/oll-23a.png", algorithm: "R U2 R' U R U' R' U2' R' F R F'" },
  { name: "23B", image: "/algorithms/megaminx/oll/oll-23b.png", algorithm: "R U2' R' U' F R' F' R U' R U' R'" },
  { name: "24A-", image: "/algorithms/megaminx/oll/oll-24a.png", algorithm: "R' U' F' U F R" },
  { name: "24A+", image: "/algorithms/megaminx/oll/oll-24a-2.png", algorithm: "F U R U' R' F'" },
  { name: "24B-", image: "/algorithms/megaminx/oll/oll-24b.png", algorithm: "R' U' F U R U' R' F' R" },
  { name: "24B+", image: "/algorithms/megaminx/oll/oll-24b-2.png", algorithm: "R U BR' U' R' U R BR R'" },
  { name: "25A-", image: "/algorithms/megaminx/oll/oll-25a.png", algorithm: "R U R2' F' U' F U R2 U2' R'" },
  { name: "25A+", image: "/algorithms/megaminx/oll/oll-25a-2.png", algorithm: "F R U R2' U' F' U F R F'" },
  { name: "25B-", image: "/algorithms/megaminx/oll/oll-25b.png", algorithm: "F R U2 R' F' U' F R U' R' F'" },
  { name: "25B+", image: "/algorithms/megaminx/oll/oll-25b-2.png", algorithm: "R' U2 R U2 R' F R' F' R U R" },
  { name: "26A-", image: "/algorithms/megaminx/oll/oll-26a.png", algorithm: "F R' U2' R F R' F' U2 R F'" },
  { name: "26A+", image: "/algorithms/megaminx/oll/oll-26a-2.png", algorithm: "R U R' U R' F R F' U R U2 R'" },
  { name: "26B-", image: "/algorithms/megaminx/oll/oll-26b.png", algorithm: "BR' U' R' U2 R U R' U2' R U BR" },
  { name: "26B+", image: "/algorithms/megaminx/oll/oll-26b-2.png", algorithm: "F U R U' BR R' F' R BR' R'" },
  { name: "27A-", image: "/algorithms/megaminx/oll/oll-27a.png", algorithm: "R2' U' R F R' U R2 U' R' F' R" },
  { name: "27A+", image: "/algorithms/megaminx/oll/oll-27a-2.png", algorithm: "F R' F R2 U' R' U' R U R' F2'" },
  { name: "27B-", image: "/algorithms/megaminx/oll/oll-27b.png", algorithm: "R' F R F' R' F R F' R U R' U' R U R'" },
  { name: "27B+", image: "/algorithms/megaminx/oll/oll-27b-2.png", algorithm: "F R' F' R U2' R U' R' U R U2 R'" },
  { name: "28-", image: "/algorithms/megaminx/oll/oll-28.png", algorithm: "x' L' U2' R U R' U L" },
  { name: "28+", image: "/algorithms/megaminx/oll/oll-28-2.png", algorithm: "x' D R2 U' R' U R' D'" },
  { name: "29-", image: "/algorithms/megaminx/oll/oll-29.png", algorithm: "BR' U2' R' U R U' R' U2 R BR" },
  { name: "29+", image: "/algorithms/megaminx/oll/oll-29-2.png", algorithm: "F U2 R U' R' U R U2' R' F'" },
  { name: "30A-", image: "/algorithms/megaminx/oll/oll-30a.png", algorithm: "BR' U2' R' U2 R BR" },
  { name: "30A+", image: "/algorithms/megaminx/oll/oll-30a-2.png", algorithm: "F U2 R U2' R' F'" },
  { name: "30B-", image: "/algorithms/megaminx/oll/oll-30b.png", algorithm: "R U' R' U R U' R' U' F R' F' R2 U R'" },
  { name: "30B+", image: "/algorithms/megaminx/oll/oll-30b-2.png", algorithm: "BR' L R' F R' F' R2 L' BR" },
  { name: "31A-", image: "/algorithms/megaminx/oll/oll-31a.png", algorithm: "BR' R' F R' F' R2 BR" },
  { name: "31A+", image: "/algorithms/megaminx/oll/oll-31a-2.png", algorithm: "F R' F' R U2' R U2 R'" },
  { name: "31B-", image: "/algorithms/megaminx/oll/oll-31b.png", algorithm: "BR' U' R' U' R U R' U R BR" },
  { name: "31B+", image: "/algorithms/megaminx/oll/oll-31b-2.png", algorithm: "F U R U R' U' R U' R' F'" },
  { name: "32A-", image: "/algorithms/megaminx/oll/oll-32a.png", algorithm: "R U R' U F' U F U' R U2' R'" },
  { name: "32A+", image: "/algorithms/megaminx/oll/oll-32a-2.png", algorithm: "R U R' U' R' F R2 U R' U' F'" },
  { name: "32B-", image: "/algorithms/megaminx/oll/oll-32b.png", algorithm: "R U R' U R' F R F' R U2' R'" },
  { name: "32B+", image: "/algorithms/megaminx/oll/oll-32b-2.png", algorithm: "R U2' R2' F R F' R U2 R'" },
  { name: "33A-", image: "/algorithms/megaminx/oll/oll-33a.png", algorithm: "R' U' R U' R' U F' U' F R U R' U R" },
  { name: "33A+", image: "/algorithms/megaminx/oll/oll-33a-2.png", algorithm: "F U R U' R' F' R' U2' R U R' U R" },
  { name: "33B-", image: "/algorithms/megaminx/oll/oll-33b.png", algorithm: "BR' U' R' U' R U R' U' R U R' U R BR" },
  { name: "33B+", image: "/algorithms/megaminx/oll/oll-33b-2.png", algorithm: "F U R U R' U' R U R' U' R U' R' F'" },
  { name: "34A", image: "/algorithms/megaminx/oll/oll-34a.png", algorithm: "F R' F' R U R U R' U R U' R' U R U2 R'" },
  { name: "34B", image: "/algorithms/megaminx/oll/oll-34b.png", algorithm: "F R' F' R U2' R U' R' U' R U' R'" },
  { name: "34C", image: "/algorithms/megaminx/oll/oll-34c.png", algorithm: "R U R' U R' F R F' U R U2' R' U R U2' R'" },
  { name: "34D", image: "/algorithms/megaminx/oll/oll-34d.png", algorithm: "F R' F' R U R U R' U R U2 R'" },
  { name: "34E-", image: "/algorithms/megaminx/oll/oll-34e.png", algorithm: "F R' F' R U R U' R2' U2' R U R' U R" },
  { name: "34E+", image: "/algorithms/megaminx/oll/oll-34e-2.png", algorithm: "F R U' R' U' R U R' F' R U2 R' U' R U' R'" },
  { name: "35A-", image: "/algorithms/megaminx/oll/oll-35a.png", algorithm: "F R' F' R U R U R' U' R U' R'" },
  { name: "35A+", image: "/algorithms/megaminx/oll/oll-35a-2.png", algorithm: "x' D R U' R U R' U' R U R2' D'" },
  { name: "35B-", image: "/algorithms/megaminx/oll/oll-35b.png", algorithm: "R U2' R2' F' U' F R2 U2' R2' U2' R" },
  { name: "35B+", image: "/algorithms/megaminx/oll/oll-35b-2.png", algorithm: "R' F R F' U' F R' F' R2 U' R'" },
  { name: "35C-", image: "/algorithms/megaminx/oll/oll-35c.png", algorithm: "R BR' R2' F R2 Br R2' F' R" },
  { name: "35C+", image: "/algorithms/megaminx/oll/oll-35c-2.png", algorithm: "R' F R2 BR' R2' F' R2 BR R'" },
  { name: "35D-", image: "/algorithms/megaminx/oll/oll-35d.png", algorithm: "BR' R' U' R U R' U' R U BR" },
  { name: "35D+", image: "/algorithms/megaminx/oll/oll-35d-2.png", algorithm: "F R U R' U' R U R' U' F'" },
  { name: "35E-", image: "/algorithms/megaminx/oll/oll-35e.png", algorithm: "F R' F' U2' R U R' U R2 U2' R'" },
  { name: "35E+", image: "/algorithms/megaminx/oll/oll-35e-2.png", algorithm: "R' U' R' F R F' R' F R F' U R" },
  { name: "35F-", image: "/algorithms/megaminx/oll/oll-35f.png", algorithm: "R U R2' F R F' U F R' F' R" },
  { name: "35F+", image: "/algorithms/megaminx/oll/oll-35f-2.png", algorithm: "F' U' F2 R' F' R U' R' F R F'" },
  { name: "36A-", image: "/algorithms/megaminx/oll/oll-36a.png", algorithm: "R U R' U2 R' F R F' R U2 R'" },
  { name: "36A+", image: "/algorithms/megaminx/oll/oll-36a-2.png", algorithm: "F U2' F' U' R' F R U2' R' F' R" },
  { name: "36B-", image: "/algorithms/megaminx/oll/oll-36b.png", algorithm: "BR' U2' R' U2' R U R' U2' R U BR" },
  { name: "36B+", image: "/algorithms/megaminx/oll/oll-36b-2.png", algorithm: "F R' F' U' F U R2 U R' U' R U' R' F'" },
  { name: "36C-", image: "/algorithms/megaminx/oll/oll-36c.png", algorithm: "R U R' U2 R U' BR U' BR' U' R'" },
  { name: "36C+", image: "/algorithms/megaminx/oll/oll-36c-2.png", algorithm: "R' U' R U2' R' U F' U F U R" },
  { name: "36D-", image: "/algorithms/megaminx/oll/oll-36d.png", algorithm: "R' U2 R U2 R2' F R F' U R" },
  { name: "36D+", image: "/algorithms/megaminx/oll/oll-36d-2.png", algorithm: "R U2' R' U' F R' F' R2 U2' R'" },
  { name: "36E-", image: "/algorithms/megaminx/oll/oll-36e.png", algorithm: "R U2' R' U F' U' F U2 R' F R F'" },
  { name: "36E+", image: "/algorithms/megaminx/oll/oll-36e-2.png", algorithm: "R U2 R' U R U' R2' F R F' R U2' R'" },
  { name: "36F-", image: "/algorithms/megaminx/oll/oll-36f.png", algorithm: "F' R U2' R2' F R F' R U2 R' F" },
  { name: "36F+", image: "/algorithms/megaminx/oll/oll-36f-2.png", algorithm: "R U2' R2' U2' R U' R' U2' F R F'" },
  { name: "37A-", image: "/algorithms/megaminx/oll/oll-37a.png", algorithm: "R U2' R2' F R F' U2' R U' R'" },
  { name: "37A+", image: "/algorithms/megaminx/oll/oll-37a-2.png", algorithm: "R' U2' F R' F' R2 U R' U R" },
  { name: "37B-", image: "/algorithms/megaminx/oll/oll-37b.png", algorithm: "y R U2' R' F' U' F U2' R' F R F'" },
  { name: "37B+", image: "/algorithms/megaminx/oll/oll-37b-2.png", algorithm: "F R' F' R U2 R U' R' U R U2' R'" },
  { name: "37C-", image: "/algorithms/megaminx/oll/oll-37c.png", algorithm: "R' U' R U' R2' F R F' U2 R" },
  { name: "37C+", image: "/algorithms/megaminx/oll/oll-37c-2.png", algorithm: "R U R' U2 F R' F' R2 U2 R'" },
  { name: "37D-", image: "/algorithms/megaminx/oll/oll-37d.png", algorithm: "R U2 R' U' R U2 R' F' U' F R U2' R'" },
  { name: "37D+", image: "/algorithms/megaminx/oll/oll-37d-2.png", algorithm: "F R' F' U' R U2' R U2 R2' U R" },
  { name: "37E-", image: "/algorithms/megaminx/oll/oll-37e.png", algorithm: "R' U' R U' R' U F' U' F U2 R" },
  { name: "37E+", image: "/algorithms/megaminx/oll/oll-37e-2.png", algorithm: "F R' F' R U2' R U2' R' U R U2' R'" },
]
