import type { AlgorithmCase } from '../types'

export const megaminxPllCases: AlgorithmCase[] = [
  { name: "A1-", image: "/algorithms/megaminx/pll/pll-a1.png", algorithm: "R' F' R U R U' R2' F R U R' F' R F U'" },
  { name: "A1+", image: "/algorithms/megaminx/pll/pll-a1-2.png", algorithm: "F' R' F R U' R' F' R2 U R' U' R' F R" },
  { name: "A2-", image: "/algorithms/megaminx/pll/pll-a2.png", algorithm: "BR' R2' U L U' R U L' U' R BR" },
  { name: "A2+", image: "/algorithms/megaminx/pll/pll-a2-2.png", algorithm: "BR' R' U L U' R' U L' U' R2 BR" },
  { name: "B1-", image: "/algorithms/megaminx/pll/pll-b1.png", algorithm: "R' U' R U R U2 R' U' R' U R2 U2' R'" },
  { name: "B1+", image: "/algorithms/megaminx/pll/pll-b1-2.png", algorithm: "R U R' U' R' U2' R U R U' R2' U2 R" },
  { name: "B2-", image: "/algorithms/megaminx/pll/pll-b2.png", algorithm: "R2' U' R2 U2' R' U2 R' U' R U R' U R2 U2' R' U' R" },
  { name: "B2+", image: "/algorithms/megaminx/pll/pll-b2-2.png", algorithm: "R2 U R2' U2 R U2' R U R' U' R U' R2' U2 R U R'" },
  { name: "C1-", image: "/algorithms/megaminx/pll/pll-c1.png", algorithm: "R' U2' R U R' U2 R U' R' U' R2 U R' U R' U' R2 U' R'" },
  { name: "C1+", image: "/algorithms/megaminx/pll/pll-c1-2.png", algorithm: "R U2 R' U' R U2' R' U R U R2' U' R U' R U R2' U R" },
  { name: "C2-", image: "/algorithms/megaminx/pll/pll-c2.png", algorithm: "R U R' U R' U2' R2 U R2' U R2 U2 R' U' R U2' R'" },
  { name: "C2+", image: "/algorithms/megaminx/pll/pll-c2-2.png", algorithm: "R' U' R U' R U2 R2' U' R2 U' R2' U2' R U R' U2 R" },
  { name: "C3-", image: "/algorithms/megaminx/pll/pll-c3.png", algorithm: "R2 U2' R2' U' R2 U R2' U2 R2 U R2' U2' R2 U2 R2'" },
  { name: "C3+", image: "/algorithms/megaminx/pll/pll-c3-2.png", algorithm: "R2' U2 R2 U R2' U' R2 U2' R2' U' R2 U2 R2' U2' R2" },
  { name: "C4-", image: "/algorithms/megaminx/pll/pll-c4.png", algorithm: "R2' U2 R2 U R2' U2 R2 U R2' U2' R2 U' R2' U2' R2" },
  { name: "C4+", image: "/algorithms/megaminx/pll/pll-c4-2.png", algorithm: "R2' U2' R2 U' R2' U2' R2 U' R2' U2 R2 U R2' U2 R2" },
  { name: "C5-", image: "/algorithms/megaminx/pll/pll-c5.png", algorithm: "R' U2' R U2' R' U2' R' U2' R U' R U R2' U2 R U R" },
  { name: "C5+", image: "/algorithms/megaminx/pll/pll-c5-2.png", algorithm: "R U2 R' U2 R U2 R U2 R' U R' U' R2 U2' R' U' R'" },
  { name: "C6-", image: "/algorithms/megaminx/pll/pll-c6.png", algorithm: "R' U R U2' R2' U' R U2' R' U R U R' U R U R" },
  { name: "C6+", image: "/algorithms/megaminx/pll/pll-c6-2.png", algorithm: "R U' R' U2 R2 U R' U2 R U' R' U' R U' R' U' R'" },
  { name: "D-", image: "/algorithms/megaminx/pll/pll-d.png", algorithm: "R' U2' R U R' U' R U' R' U2 R U2' R' U2' R" },
  { name: "D+", image: "/algorithms/megaminx/pll/pll-d-2.png", algorithm: "R U2 R' U' R U R' U R U2' R' U2 R U2 R'" },
  { name: "E1", image: "/algorithms/megaminx/pll/pll-e1.png", algorithm: "R U R' U R' U' R F' R U R' U' R' F R2 U' R2' U R" },
  { name: "E2", image: "/algorithms/megaminx/pll/pll-e2.png", algorithm: "x' R U' R' dR R U R' dR' R U R' dR R U' R' dR' x" },
  { name: "E3", image: "/algorithms/megaminx/pll/pll-e3.png", algorithm: "L' R U2 R' U' R U R' U' R U R' U' R U' R' L" },
  { name: "F1-", image: "/algorithms/megaminx/pll/pll-f1.png", algorithm: "R2 U2' R2' U' R2 U2' R2'" },
  { name: "F1+", image: "/algorithms/megaminx/pll/pll-f1-2.png", algorithm: "R2 U2 R2' U R2 U2 R2'" },
  { name: "F2-", image: "/algorithms/megaminx/pll/pll-f2.png", algorithm: "R' U' R U2' R U2 R2' U R U' R U2' R'" },
  { name: "F2+", image: "/algorithms/megaminx/pll/pll-f2-2.png", algorithm: "R U R' U2 R' U2' R2 U' R' U R' U2 R" },
  { name: "F3-", image: "/algorithms/megaminx/pll/pll-f3.png", algorithm: "R U2 R' U R' U' R2 U2' R' U2 R' U R" },
  { name: "F3+", image: "/algorithms/megaminx/pll/pll-f3-2.png", algorithm: "R' U2' R U' R U R2' U2 R U2' R U' R'" },
  { name: "F4-", image: "/algorithms/megaminx/pll/pll-f4.png", algorithm: "R' U' R U' R2' U2 R2 U2 R' U2' R' U2' R U2 R" },
  { name: "F4+", image: "/algorithms/megaminx/pll/pll-f4-2.png", algorithm: "R U R' U R2 U2' R2' U2' R U2 R U2 R' U2' R'" },
  { name: "F5-", image: "/algorithms/megaminx/pll/pll-f5.png", algorithm: "R' U2' R' U2 R U2 R U2' R2' U2' R2 U R' U R" },
  { name: "F5+", image: "/algorithms/megaminx/pll/pll-f5-2.png", algorithm: "R U2 R U2' R' U2' R' U2 R2 U2 R2' U' R U' R'" },
  { name: "G1-", image: "/algorithms/megaminx/pll/pll-g1.png", algorithm: "R U2' R2' U2 R U2' R U' R' U2' R U' R2' U2' R2 U2 R'" },
  { name: "G1+", image: "/algorithms/megaminx/pll/pll-g1-2.png", algorithm: "R' U2 R2 U2' R' U2 R' U R U2 R' U R2 U2 R2' U2' R" },
  { name: "G2-", image: "/algorithms/megaminx/pll/pll-g2.png", algorithm: "F U2' R' U' R F' R' U' R F U' R' U2' R U2 F'" },
  { name: "G2+", image: "/algorithms/megaminx/pll/pll-g2-2.png", algorithm: "R U2' R' U' R U2' R2' U2 L U' R U L' R' U2' R" },
  { name: "H1-", image: "/algorithms/megaminx/pll/pll-h1.png", algorithm: "R U R' U R' U' R2 U' R' U R' U R U R U R' U R' U' R2 U' R' U R' U R" },
  { name: "H1+", image: "/algorithms/megaminx/pll/pll-h1-2.png", algorithm: "R' dR R U R' dR' R U R' dR R U R' dR' R U R' dR R U R' dR' R" },
  { name: "H2-", image: "/algorithms/megaminx/pll/pll-h2.png", algorithm: "R2' U2' R2 U R2' U R2 y R2 U R2' U R2 U2' R2'" },
  { name: "H2+", image: "/algorithms/megaminx/pll/pll-h2-2.png", algorithm: "R2 U2 R2' U' R2 U' R2' y' R2' U' R2 U' R2' U2 R2" },
  { name: "I1-", image: "/algorithms/megaminx/pll/pll-i1.png", algorithm: "R2 U2' R2' U' R2 BR2' U R2' U' R2 U' BR2 U' R2'" },
  { name: "I1+", image: "/algorithms/megaminx/pll/pll-i1-2.png", algorithm: "R2' U2 R2 U R2' F2 U' R2 U R2' U F2' U R2" },
  { name: "I2-", image: "/algorithms/megaminx/pll/pll-i2.png", algorithm: "R2 U BR2' U R2' U R2 U' BR2 R2' U R2 U2 R2'" },
  { name: "I2+", image: "/algorithms/megaminx/pll/pll-i2-2.png", algorithm: "R2' U' F2 U' R2 U' R2' U F2' R2 U' R2' U2' R2" },
  { name: "I3-", image: "/algorithms/megaminx/pll/pll-i3.png", algorithm: "R U2' R2' U2' R U2 R U2 R' U2' R' U' R U2 R' U R" },
  { name: "I3+", image: "/algorithms/megaminx/pll/pll-i3-2.png", algorithm: "R' U2 R2 U2 R' U2' R' U2' R U2 R U R' U2' R U' R'" },
  { name: "I4-", image: "/algorithms/megaminx/pll/pll-i4.png", algorithm: "R' U2 R U R' U R' U2' R U R' U R2 U' R' U2 R" },
  { name: "I4+", image: "/algorithms/megaminx/pll/pll-i4-2.png", algorithm: "R' U' R' U2' F' R U R U' R' F R' U2 R U R" },
  { name: "I5-", image: "/algorithms/megaminx/pll/pll-i5.png", algorithm: "R' U2' R U R2' U' R U' R' U2 R U' R U' R' U2' R" },
  { name: "I5+", image: "/algorithms/megaminx/pll/pll-i5-2.png", algorithm: "R' U' R' U2' R F' R U R' U' R' F U2 R U R" },
  { name: "I6-", image: "/algorithms/megaminx/pll/pll-i6.png", algorithm: "R2' F2 R2 U' R2' F2' R2 U2 R2' F2 R2 U' R2' F2' R2" },
  { name: "I6+", image: "/algorithms/megaminx/pll/pll-i6-2.png", algorithm: "R2 BR2' R2' U' R2 BR2 R2' U2 R2 BR2' R2' U' R2 BR2 R2'" },
  { name: "J1-", image: "/algorithms/megaminx/pll/pll-j1.png", algorithm: "F U' R' F R2 U' R' U' R U R' F' R U R' F'" },
  { name: "J1+", image: "/algorithms/megaminx/pll/pll-j1-2.png", algorithm: "R U R' F' R U R' U' R' F R2 U' R'" },
  { name: "J2-", image: "/algorithms/megaminx/pll/pll-j2.png", algorithm: "R U2 R' U2' R U' R' U' R' U2' R U R' U R2 U R'" },
  { name: "J2+", image: "/algorithms/megaminx/pll/pll-j2-2.png", algorithm: "R' U2' R U2 R' U R U R U2 R' U' R U' R2' U' R" },
  { name: "J3-", image: "/algorithms/megaminx/pll/pll-j3.png", algorithm: "F U F' R2' F U' F U' R2 U R2' U F2' R2" },
  { name: "J3+", image: "/algorithms/megaminx/pll/pll-j3-2.png", algorithm: "R U R' U' R' U2' R U R U R2' U R2 U2 R2' U2' R" },
  { name: "K1-", image: "/algorithms/megaminx/pll/pll-k1.png", algorithm: "R2 U2' R2' U' R2 U R2' U' R2 U R2' U' R2 U2' R2'" },
  { name: "K1+", image: "/algorithms/megaminx/pll/pll-k1-2.png", algorithm: "R2' U2 R2 U R2' U' R2 U R2' U' R2 U R2' U2 R2" },
  { name: "K2-", image: "/algorithms/megaminx/pll/pll-k2.png", algorithm: "R2 U2' R2' U' R2 U2' R' U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: "K2+", image: "/algorithms/megaminx/pll/pll-k2-2.png", algorithm: "R' U2 R U' R' U2 R U2' R' U' R U2' R' U R U2' R' U R" },
  { name: "L1", image: "/algorithms/megaminx/pll/pll-l1.png", algorithm: "R' U2 R U R' U R U' R' U2 R U' R U R' U R U2' R'" },
  { name: "L2", image: "/algorithms/megaminx/pll/pll-l2.png", algorithm: "R U2 R' U R U' R' U' R U' R2' U' R U' R' U' R U R' U2 R" },
  { name: "L3-", image: "/algorithms/megaminx/pll/pll-l3.png", algorithm: "R U R' U' R' U2 R U R U R2' U R U' R U R' U' R U2' R'" },
  { name: "L3+", image: "/algorithms/megaminx/pll/pll-l3-2.png", algorithm: "F U2' F' U2' R F R' U' R F' U2' R' U' R U2' R'" },
  { name: "L4-", image: "/algorithms/megaminx/pll/pll-l4.png", algorithm: "R U2' R' U R U2 R U2 R' U R' U' R U' R U' R' U' R'" },
  { name: "L4+", image: "/algorithms/megaminx/pll/pll-l4-2.png", algorithm: "R U R U R' U R' U R U' R U2' R' U2' R' U' R U2 R'" },
  { name: "L5-", image: "/algorithms/megaminx/pll/pll-l5.png", algorithm: "R U2 R' U' R U' R2' U2 R U R' U' R U2 R' U R" },
  { name: "L5+", image: "/algorithms/megaminx/pll/pll-l5-2.png", algorithm: "R' U2' R U R' U R2 U2' R' U' R U R' U2' R U' R'" },
  { name: "L6-", image: "/algorithms/megaminx/pll/pll-l6.png", algorithm: "R' U' R U2' R' U R U' R' U2' R2 U R' U R U2' R'" },
  { name: "L6+", image: "/algorithms/megaminx/pll/pll-l6-2.png", algorithm: "R U R' U2 R U' R' U R U2 R2' U' R U' R' U2 R" },
  { name: "M", image: "/algorithms/megaminx/pll/pll-m.png", algorithm: "R U R' U2' R' U2' R U R' U R2 U' R' U2 R U' R' U R U' R'" },
  { name: "N1-", image: "/algorithms/megaminx/pll/pll-n1.png", algorithm: "R' U2 R' U2' R U' R' U2' R U2 R" },
  { name: "N1+", image: "/algorithms/megaminx/pll/pll-n1-2.png", algorithm: "y2' R U2 R U2' R' U' R U2' R' U2 R'" },
  { name: "N2-", image: "/algorithms/megaminx/pll/pll-n2.png", algorithm: "R' L' U2' R U' L R' U L' U2' R U2' L" },
  { name: "N2-", image: "/algorithms/megaminx/pll/pll-n2-2.png", algorithm: "R L U2 L' U R' L U' R U2 L' U2 R'" },
  { name: "P1-", image: "/algorithms/megaminx/pll/pll-p1.png", algorithm: "R' U' R' F R U R U' R' y' R2' U' R U' R' U2 R BR" },
  { name: "P1+", image: "/algorithms/megaminx/pll/pll-p1-2.png", algorithm: "R' F R2 U R' U R U2' R' U R' F' R F U' F'" },
  { name: "P2-", image: "/algorithms/megaminx/pll/pll-p2.png", algorithm: "BR' R' U2' R U R' U R2 BR BL' BR' R' BR BL" },
  { name: "P2+", image: "/algorithms/megaminx/pll/pll-p2-2.png", algorithm: "F U F' R' F R U' R U2 R' U' R U' R2' F' R" },
  { name: "P3-", image: "/algorithms/megaminx/pll/pll-p3.png", algorithm: "R' U' R2 U' R2' U2 R U R U2' R U R2' U R2 U2' R2'" },
  { name: "P3+", image: "/algorithms/megaminx/pll/pll-p3-2.png", algorithm: "R U R2' U R2 U2' R' U' R' U2 R' U' R2 U' R2' U2 R2" },
  { name: "P4-", image: "/algorithms/megaminx/pll/pll-p4.png", algorithm: "R2 U2 R2' U' R2 U' R' U2 R' U' R' U2' R2 U R2' U R" },
  { name: "P4+", image: "/algorithms/megaminx/pll/pll-p4-2.png", algorithm: "R2' U2' R2 U R2' U R U2' R U R U2 R2' U' R2 U' R'" },
  { name: "Q1-", image: "/algorithms/megaminx/pll/pll-q1.png", algorithm: "R2 U2' R2' U' R2 U2' R2' U R2 U2' R2' U' R2 U2' R2'" },
  { name: "Q1+", image: "/algorithms/megaminx/pll/pll-q1-2.png", algorithm: "R2' U2 R2 U R2' U2 R2 U' R2' U2 R2 U R2' U2 R2" },
  { name: "Q2-", image: "/algorithms/megaminx/pll/pll-q2.png", algorithm: "R U2 R' U R U2 R2' U2 R U R' U2 R" },
  { name: "Q2+", image: "/algorithms/megaminx/pll/pll-q2-2.png", algorithm: "R' U2' R U' R' U2' R2 U2' R' U' R U2' R'" },
  { name: "R1-", image: "/algorithms/megaminx/pll/pll-r1.png", algorithm: "R U2' R' U R2 U2' R2' U' R U R U2 R' U R'" },
  { name: "R1+", image: "/algorithms/megaminx/pll/pll-r1-2.png", algorithm: "R' U2 R U' R2' U2 R2 U R' U' R' U2' R U' R" },
  { name: "R2-", image: "/algorithms/megaminx/pll/pll-r2.png", algorithm: "R U' R U2' R' U' R' U R2 U2 R2' U' R U2 R'" },
  { name: "R2+", image: "/algorithms/megaminx/pll/pll-r2-2.png", algorithm: "R' U R' U2 R U R U' R2' U2' R2 U R' U2' R" },
  { name: "R3-", image: "/algorithms/megaminx/pll/pll-r3.png", algorithm: "R' U' R2 U' R' U' R' U R U R' U R2 U R' U R U' R'" },
  { name: "R3+", image: "/algorithms/megaminx/pll/pll-r3-2.png", algorithm: "R U R2' U R U R U' R' U' R U' R2' U' R U' R' U R" },
  { name: "R4-", image: "/algorithms/megaminx/pll/pll-r4.png", algorithm: "R U R' U' R U' R2' U' R U' R' U' R U R U R2' U R" },
  { name: "R4+", image: "/algorithms/megaminx/pll/pll-r4-2.png", algorithm: "R' U' R U R' U R2 U R' U R U R' U' R' U' R2 U' R'" },
  { name: "S1-", image: "/algorithms/megaminx/pll/pll-s1.png", algorithm: "R' U' R U2' R' U2' R U R U R' U R U2' R'" },
  { name: "S1+", image: "/algorithms/megaminx/pll/pll-s1-2.png", algorithm: "R U R' U2 R U2 R' U' R' U' R U' R' U2 R" },
  { name: "S2-", image: "/algorithms/megaminx/pll/pll-s2.png", algorithm: "R2' U2 R2 U2 R2' U R U2' R U R U2 R2' U' R2 U' R'" },
  { name: "S2+", image: "/algorithms/megaminx/pll/pll-s2-2.png", algorithm: "R2 U2' R2' U2' R2 U' R' U2 R' U' R' U2' R2 U R2' U R" },
  { name: "S3-", image: "/algorithms/megaminx/pll/pll-s3.png", algorithm: "R U R2' U R2 U2' R' U' R' U2 R' U' R2 U2' R2' U2' R2" },
  { name: "S3+", image: "/algorithms/megaminx/pll/pll-s3-2.png", algorithm: "R' U' R2 U' R2' U2 R U R U2' R U R2' U2 R2 U2 R2'" },
  { name: "S4-", image: "/algorithms/megaminx/pll/pll-s4.png", algorithm: "R2' U2 R2 U R2' U2 R2 U' R2' U2' R2 U' R2' U2' R2" },
  { name: "S4+", image: "/algorithms/megaminx/pll/pll-s4-2.png", algorithm: "R2' U2' R2 U' R2' U2' R2 U R2' U2 R2 U R2' U2 R2" },
  { name: "S5-", image: "/algorithms/megaminx/pll/pll-s5.png", algorithm: "R' U' R' U2' R2 U' R' U R' U2 R U2 R U2 R' U2 R" },
  { name: "S5+", image: "/algorithms/megaminx/pll/pll-s5-2.png", algorithm: "R U R U2 R2' U R U' R U2' R' U2' R' U2' R U2' R'" },
  { name: "S6-", image: "/algorithms/megaminx/pll/pll-s6.png", algorithm: "R' U' R' U' R U' R' U' R U2 R' U R2 U2 R' U' R" },
  { name: "S6+", image: "/algorithms/megaminx/pll/pll-s6-2.png", algorithm: "R U R U R' U R U R' U2' R U' R2' U2' R U R'" },
  { name: "T1", image: "/algorithms/megaminx/pll/pll-t1.png", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: "T2-", image: "/algorithms/megaminx/pll/pll-t2.png", algorithm: "R2' F R U R U' R' F' R U2' R' U2 R" },
  { name: "T2+", image: "/algorithms/megaminx/pll/pll-t2-2.png", algorithm: "R' U2' R U2 R' F R U R' U' R' F' R2" },
  { name: "T3-", image: "/algorithms/megaminx/pll/pll-t3.png", algorithm: "R2 U2' R2' U' R2 U R2' U' R2 U2' R2'" },
  { name: "T3+", image: "/algorithms/megaminx/pll/pll-t3-2.png", algorithm: "R2' U2 R2 U R2' U' R2 U R2' U2 R2" },
  { name: "T4-", image: "/algorithms/megaminx/pll/pll-t4.png", algorithm: "R' U' R U2' R2' U2' R2 U' R2' U2' R2 U R' U R" },
  { name: "T4+", image: "/algorithms/megaminx/pll/pll-t4-2.png", algorithm: "R U R' F' R U R' U' R' F R U' R' F R2 U' R' U' R U R' F'" },
  { name: "U1-", image: "/algorithms/megaminx/pll/pll-u1.png", algorithm: "R U R' U R' U' R2 U' R' U R' U R" },
  { name: "U1+", image: "/algorithms/megaminx/pll/pll-u1-2.png", algorithm: "R' U' R U' R U R2' U R U' R U' R'" },
  { name: "U2-", image: "/algorithms/megaminx/pll/pll-u2.png", algorithm: "R U2 R' U R' U' R2 U' R' U R' U R U2' R U' R'" },
  { name: "U2+", image: "/algorithms/megaminx/pll/pll-u2-2.png", algorithm: "R U R' U2 R' U' R U' R U R2' U R U' R U2' R'" },
  { name: "V1-", image: "/algorithms/megaminx/pll/pll-v1.png", algorithm: "R U2 R2' F R F' R U' R' F' U F R U' R'" },
  { name: "V1+", image: "/algorithms/megaminx/pll/pll-v1-2.png", algorithm: "R' U2 R' dR' R U' R' dR R U R U' R' U' R" },
  { name: "V2-", image: "/algorithms/megaminx/pll/pll-v2.png", algorithm: "R U' R' F U R U' R' F' R U R' F' U' F R U R'" },
  { name: "V2+", image: "/algorithms/megaminx/pll/pll-v2-2.png", algorithm: "R' U R U R' U' R' dR' R U R' dR R U2' R" },
  { name: "V3-", image: "/algorithms/megaminx/pll/pll-v3.png", algorithm: "R' U' R2' U R U R' U' R U R U' R2 U' R' U R'" },
  { name: "V3+", image: "/algorithms/megaminx/pll/pll-v3-2.png", algorithm: "R U R2 U' R' U' R U R' U' R' U R2' U R U' R" },
  { name: "V4-", image: "/algorithms/megaminx/pll/pll-v4.png", algorithm: "R U' R U R2' U R' U' R' U R U' R' U' R2 U R" },
  { name: "V4+", image: "/algorithms/megaminx/pll/pll-v4-2.png", algorithm: "R' U R' U' R2 U' R U R U' R' U R U R2' U' R'" },
  { name: "W", image: "/algorithms/megaminx/pll/pll-w.png", algorithm: "R' U2' R' U2 R U2 R U' R2' U2 R2 U2 R' U R" },
  { name: "X1", image: "/algorithms/megaminx/pll/pll-x1.png", algorithm: "F U2 R U2' R' U R U R' U2' F' R' U' R U2' R' U2' R" },
  { name: "X2", image: "/algorithms/megaminx/pll/pll-x2.png", algorithm: "F R U R' F U R' U' F' U R2 U2' R' F'" },
  { name: "X3", image: "/algorithms/megaminx/pll/pll-x3.png", algorithm: "R' U' R U' R' U2 R2 U R' U2 R' U2' R2 U' R' U2 R' U R" },
  { name: "X4", image: "/algorithms/megaminx/pll/pll-x4.png", algorithm: "R' U' R2 U' R' U R U' R2' U' R2 U R' U' R U R2' U2 R" },
  { name: "X5-", image: "/algorithms/megaminx/pll/pll-x5.png", algorithm: "R2' U' R U2' R' U R U R' U R2 U' R' U2' R U2' R' U' R" },
  { name: "X5+", image: "/algorithms/megaminx/pll/pll-x5-2.png", algorithm: "R' U R U2 R' U2 R U R2' U' R U' R' U' R U2 R' U R2" },
  { name: "X6-", image: "/algorithms/megaminx/pll/pll-x6.png", algorithm: "R U2' R U R2' U R U R' U' R U' R U' R2' U R U2 R'" },
  { name: "X6+", image: "/algorithms/megaminx/pll/pll-x6-2.png", algorithm: "R' U2 R' U' R2 U' R' U' R U R' U R' U R2 U' R' U2' R" },
  { name: "X7-", image: "/algorithms/megaminx/pll/pll-x7.png", algorithm: "R U R2' F' R U2' R U' R' U2' R' F R U R U R' U2' R U' R'" },
  { name: "X7+", image: "/algorithms/megaminx/pll/pll-x7-2.png", algorithm: "R U R' U' F' U' F U R U R' U R U2' F R' F' R U R U' R2'" },
  { name: "Y1-", image: "/algorithms/megaminx/pll/pll-y1.png", algorithm: "F R' F' R U R U' R' F R U' R' U R U R' F'" },
  { name: "Y1+", image: "/algorithms/megaminx/pll/pll-y1-2.png", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
  { name: "Y2-", image: "/algorithms/megaminx/pll/pll-y2.png", algorithm: "R2' U2 R2 U2' R2' U R2 U2' R2' U2 R2" },
  { name: "Y2+", image: "/algorithms/megaminx/pll/pll-y2-2.png", algorithm: "R2 U2' R2' U2 R2 U' R2' U2 R2 U2' R2'" },
  { name: "Y3-", image: "/algorithms/megaminx/pll/pll-y3.png", algorithm: "R2' U' R2 U' R2' U2 R2 U2' R2' U' R2 U' R2' U2 R2" },
  { name: "Y3+", image: "/algorithms/megaminx/pll/pll-y3-2.png", algorithm: "y R2 U R2' U R2 U2' R2' U2 R2 U R2' U R2 U2' R2'" },
  { name: "Z1", image: "/algorithms/megaminx/pll/pll-z1.png", algorithm: "R' U' F R U' R' U' R U2 R' F' R F U' F' R' U2 R" },
  { name: "Z2", image: "/algorithms/megaminx/pll/pll-z2.png", algorithm: "R' U2' R' U' R F R' F' U R F' U' F U2' R" },
  { name: "Z3", image: "/algorithms/megaminx/pll/pll-z3.png", algorithm: "R' L' U2 L U R BR F U2' BR' U' F'" },
]
