import type { AlgorithmCase } from '../../types'

export const fourByFourPllCases: AlgorithmCase[] = [
  { name: "Adj-C", image: "/algorithms/4x4/pll/4x4-pll-adj-c.png", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F' U' [*]" },
  { name: "Ba", image: "/algorithms/4x4/pll/4x4-pll-ba.png", algorithm: "[*] U R U R' F' R U R' U' R' F R2 U' R'" },
  { name: "Bb", image: "/algorithms/4x4/pll/4x4-pll-bb.png", algorithm: "R U R' U' R' F R2 U' R' [*] U R U R' F'" },
  { name: "Ca", image: "/algorithms/4x4/pll/4x4-pll-ca.png", algorithm: "[*] U R' U2 R U2 R' F R U R' U' R' F' R2" },
  { name: "Cb", image: "/algorithms/4x4/pll/4x4-pll-cb.png", algorithm: "[*] R U R' F' R U2 R' U2 R' F R U R U2 R'" },
  { name: "Da", image: "/algorithms/4x4/pll/4x4-pll-da.png", algorithm: "R' U L' U2 R U' R' U2 R L U' [*]" },
  { name: "Db", image: "/algorithms/4x4/pll/4x4-pll-db.png", algorithm: "R U R' F' R U R' U' R' F R2 U' R' [*]" },
  { name: "Ka", image: "/algorithms/4x4/pll/4x4-pll-ka.png", algorithm: "[*] x R2 D2 R U R' D2 R U' R" },
  { name: "Kb", image: "/algorithms/4x4/pll/4x4-pll-kb.png", algorithm: "[*] U x R' U R' D2 R U' R' D2 R2" },
  { name: "M", image: "/algorithms/4x4/pll/4x4-pll-m.png", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F' [*]" },
  { name: "Pa", image: "/algorithms/4x4/pll/4x4-pll-pa.png", algorithm: "R U R' F' R U R' U' R' F R2 U' R' U' [*]" },
  { name: "Pb", image: "/algorithms/4x4/pll/4x4-pll-pb.png", algorithm: "[*] R U R' F' R U R' U' R' F R2 U' R'" },
  { name: "Diag-C", image: "/algorithms/4x4/pll/4x4-pll-diag-c.png", algorithm: "F R U' R' U' R U R' F' U' [*] U' R U R' U' R' F R F'" },
  { name: "Q", image: "/algorithms/4x4/pll/4x4-pll-q.png", algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x U [*]" },
  { name: "Sa", image: "/algorithms/4x4/pll/4x4-pll-sa.png", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F' U' [*]" },
  { name: "Sb", image: "/algorithms/4x4/pll/4x4-pll-sb.png", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F' [*]" },
  { name: "X", image: "/algorithms/4x4/pll/4x4-pll-x.png", algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x [*]" },
  { name: "Adj-E", image: "/algorithms/4x4/pll/4x4-pll-adj-e.png", algorithm: "R U R' U' [*] U' R U' R'" },
  { name: "O+", image: "/algorithms/4x4/pll/4x4-pll-o.png", algorithm: "M' U' M2 U' M2 U' M' U2 M2 [*]" },
  { name: "O-", image: "/algorithms/4x4/pll/4x4-pll-o-2.png", algorithm: "M' U' M2 U' M2 U' M' U2 M2 U' [*]" },
  { name: "Pure-E", image: "/algorithms/4x4/pll/4x4-pll-pure-e.png", algorithm: "[*]" },
  { name: "W", image: "/algorithms/4x4/pll/4x4-pll-w.png", algorithm: "R U' R U R U R U' R' U' R2 [*]" },
]
