import type { AlgorithmCase } from '../types'

export const twoByTwoEgTwoCases: AlgorithmCase[] = [
  { name: "EG2 AS 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-as-1.svg", algorithm: "F R2 U R' U2 R U R2 U F'" },
  { name: "EG2 AS 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-as-2.svg", algorithm: "R' U' R U' R' U2 R' F2 R2" },
  { name: "EG2 AS 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-as-3.svg", algorithm: "U2 R' F R F' R U R B2 R2" },
  { name: "EG2 AS 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-as-4.svg", algorithm: "U2 F' L F L' U2 L' U2 L' B2 L2" },
  { name: "EG2 AS 5", image: "/algorithms/2x2/eg-2/eg-2-eg2-as-5.svg", algorithm: "y2 F R F' U R2 F' R U' R" },
  { name: "EG2 AS 6", image: "/algorithms/2x2/eg-2/eg-2-eg2-as-6.svg", algorithm: "y2 R2 F2 R F R F' R U R'" },
  { name: "EG2 H 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-h-1.svg", algorithm: "R2 F U2 F2 R2 F' R2" },
  { name: "EG2 H 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-h-2.svg", algorithm: "y R2 B2 U2 R' U2 R2" },
  { name: "EG2 H 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-h-3.svg", algorithm: "R' U' R U2 R2 F' R U' F R" },
  { name: "EG2 H 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-h-4.svg", algorithm: "y' R U2 B2 R' U R U' B R'" },
  { name: "EG2 L 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-l-1.svg", algorithm: "U L2 B2 L U' L' U L F' L F" },
  { name: "EG2 L 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-l-2.svg", algorithm: "y2 F2 R2 F R U R' U' R' F R" },
  { name: "EG2 L 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-l-3.svg", algorithm: "y2 R2 U' R U2 R' U2 R U' F2 R2" },
  { name: "EG2 L 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-l-4.svg", algorithm: "y' R' U L' U2 R' F R U' R' U' F' x2" },
  { name: "EG2 L 5", image: "/algorithms/2x2/eg-2/eg-2-eg2-l-5.svg", algorithm: "y F R' F' R U R U' R B2 R2" },
  { name: "EG2 L 6", image: "/algorithms/2x2/eg-2/eg-2-eg2-l-6.svg", algorithm: "y2 F' R U R' U' R' F R' F2 R2" },
  { name: "EG2 Pi 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-pi-1.svg", algorithm: "F U' R U2 R U' R' U R' F'" },
  { name: "EG2 Pi 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-pi-2.svg", algorithm: "R U2 R2 U R' F2 R2 F'" },
  { name: "EG2 Pi 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-pi-3.svg", algorithm: "U F R2 U' R2 U R2 U R2 F R2 F2 U2" },
  { name: "EG2 Pi 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-pi-4.svg", algorithm: "y2 R' F R F' R U' R' U' R U' R F2 R2" },
  { name: "EG2 Pi 5", image: "/algorithms/2x2/eg-2/eg-2-eg2-pi-5.svg", algorithm: "U' R' F' R' F2 R2 U R' U2 R U" },
  { name: "EG2 Pi 6", image: "/algorithms/2x2/eg-2/eg-2-eg2-pi-6.svg", algorithm: "U R' U2 R U' R2 F2 R F R U'" },
  { name: "EG2 S 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-s-1.svg", algorithm: "R2 F2 R U R U' R' F R' F' R2 U R' U' R" },
  { name: "EG2 S 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-s-2.svg", algorithm: "R U R' U R U2 R B2 R2" },
  { name: "EG2 S 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-s-3.svg", algorithm: "R U' R' F R' F' R' F2 R2" },
  { name: "EG2 S 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-s-4.svg", algorithm: "F R' F' R U2 R U2 R B2 R2" },
  { name: "EG2 S 5", image: "/algorithms/2x2/eg-2/eg-2-eg2-s-5.svg", algorithm: "R' U R' F R2 U' F R' F'" },
  { name: "EG2 S 6", image: "/algorithms/2x2/eg-2/eg-2-eg2-s-6.svg", algorithm: "R2 B2 R' U' R' F R' F' R" },
  { name: "EG2 T 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-t-1.svg", algorithm: "U R' F' R U R U' R' F' R2 B2 U" },
  { name: "EG2 T 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-t-2.svg", algorithm: "y' F U' R2 U' R' U R2 F'" },
  { name: "EG2 T 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-t-3.svg", algorithm: "R' U R U2 R2 F' R U' R" },
  { name: "EG2 T 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-t-4.svg", algorithm: "R2 F2 R U' F R' F' R U R" },
  { name: "EG2 T 5", image: "/algorithms/2x2/eg-2/eg-2-eg2-t-5.svg", algorithm: "y' R' U2 R U' R' F R' F R F' R" },
  { name: "EG2 T 6", image: "/algorithms/2x2/eg-2/eg-2-eg2-t-6.svg", algorithm: "y R' U2 R' F2 R F2 R" },
  { name: "EG2 U 1", image: "/algorithms/2x2/eg-2/eg-2-eg2-u-1.svg", algorithm: "R2 U2 R U R' U F' R U' R" },
  { name: "EG2 U 2", image: "/algorithms/2x2/eg-2/eg-2-eg2-u-2.svg", algorithm: "y' F R U R' U' F R2 B2" },
  { name: "EG2 U 3", image: "/algorithms/2x2/eg-2/eg-2-eg2-u-3.svg", algorithm: "R' F' U' R U2 R' U F R" },
  { name: "EG2 U 4", image: "/algorithms/2x2/eg-2/eg-2-eg2-u-4.svg", algorithm: "R' F' U' F U2 L' U2 R U' L" },
  { name: "EG2 U 5", image: "/algorithms/2x2/eg-2/eg-2-eg2-u-5.svg", algorithm: "y2 R2 B2 R' U R' U' R' F R F'" },
  { name: "EG2 U 6", image: "/algorithms/2x2/eg-2/eg-2-eg2-u-6.svg", algorithm: "y2 R2 F2 R F' R U L F' L' F" },
]
