import type { AlgorithmCase } from '../types'

export const pyraminxL4eCases: AlgorithmCase[] = [
  { name: "Sune", image: "/algorithms/pyraminx/l4e/l4e-sune.png", algorithm: "R U R' U R U R'" },
  { name: "AntiSune", image: "/algorithms/pyraminx/l4e/l4e-antisune.png", algorithm: "R U' R' U' R U' R'" },
  { name: "Lefty Bars", image: "/algorithms/pyraminx/l4e/l4e-lefty-bars.png", algorithm: "R' U' L' U L R" },
  { name: "Righty Bars", image: "/algorithms/pyraminx/l4e/l4e-righty-bars.png", algorithm: "L U R U' R' L'" },
  { name: "Sledge", image: "/algorithms/pyraminx/l4e/l4e-sledge.png", algorithm: "R' L R L'" },
  { name: "Hedge", image: "/algorithms/pyraminx/l4e/l4e-hedge.png", algorithm: "L R' L' R" },
  { name: "Clockwise", image: "/algorithms/pyraminx/l4e/l4e-clockwise.png", algorithm: "L R' L' R2 U' R'" },
  { name: "Counterclockwise", image: "/algorithms/pyraminx/l4e/l4e-counterclockwise.png", algorithm: "R' L R L2' U L" },
  { name: "Righty", image: "/algorithms/pyraminx/l4e/l4e-righty.png", algorithm: "R U' R'" },
  { name: "Lefty", image: "/algorithms/pyraminx/l4e/l4e-lefty.png", algorithm: "L' U L" },
  { name: "Sexy", image: "/algorithms/pyraminx/l4e/l4e-sexy.png", algorithm: "U' R U R'" },
  { name: "Left Sexy", image: "/algorithms/pyraminx/l4e/l4e-left-sexy.png", algorithm: "U L' U' L" },
  { name: "2 Flip", image: "/algorithms/pyraminx/l4e/l4e-2-flip.png", algorithm: "R' L R L' U L' U' L" },
  { name: "DR Flip", image: "/algorithms/pyraminx/l4e/l4e-dr-flip.png", algorithm: "L' U L U' R U' R'" },
  { name: "DL Flip", image: "/algorithms/pyraminx/l4e/l4e-dl-flip.png", algorithm: "R' L R L' R U' R'" },
  { name: "DB Flip", image: "/algorithms/pyraminx/l4e/l4e-db-flip.png", algorithm: "R U R' U L' U' L" },
  { name: "4 Flip", image: "/algorithms/pyraminx/l4e/l4e-4-flip.png", algorithm: "L' U L R U' R' L' U L R U' R'" },
  { name: "Right Polish Flip", image: "/algorithms/pyraminx/l4e/l4e-right-polish-flip.png", algorithm: "R U' R' L' U' L" },
  { name: "Left Polish Flip", image: "/algorithms/pyraminx/l4e/l4e-left-polish-flip.png", algorithm: "L' U L R U R'" },
  { name: "SUS", image: "/algorithms/pyraminx/l4e/l4e-sus.png", algorithm: "R' L R L' U' R' L R L'" },
  { name: "Anti SUS", image: "/algorithms/pyraminx/l4e/l4e-anti-sus.png", algorithm: "L R' L' R U L R' L' R" },
  { name: "Good Niky", image: "/algorithms/pyraminx/l4e/l4e-good-niky.png", algorithm: "R U' R' L' U L" },
  { name: "Good Sochi", image: "/algorithms/pyraminx/l4e/l4e-good-sochi.png", algorithm: "L' U L R U' R'" },
  { name: "Super Sledge", image: "/algorithms/pyraminx/l4e/l4e-super-sledge.png", algorithm: "R U' R2' L R L'" },
  { name: "Super Hedge", image: "/algorithms/pyraminx/l4e/l4e-super-hedge.png", algorithm: "L' U L2' R' L' R" },
  { name: "Bad Niky", image: "/algorithms/pyraminx/l4e/l4e-bad-niky.png", algorithm: "R U' R' U' L' U L" },
  { name: "Bad Sochi", image: "/algorithms/pyraminx/l4e/l4e-bad-sochi.png", algorithm: "L' U L U R U' R'" },
  { name: "Right Spam", image: "/algorithms/pyraminx/l4e/l4e-right-spam.png", algorithm: "R U R' U R' L R L'" },
  { name: "Left Spam", image: "/algorithms/pyraminx/l4e/l4e-left-spam.png", algorithm: "L' U' L U' L R' L' R" },
  { name: "Bad Sledge", image: "/algorithms/pyraminx/l4e/l4e-bad-sledge.png", algorithm: "L R' L' R U' R U' R'" },
  { name: "Bad Hedge", image: "/algorithms/pyraminx/l4e/l4e-bad-hedge.png", algorithm: "R' L R L' U L' U L" },
  { name: "Bad Sexy", image: "/algorithms/pyraminx/l4e/l4e-bad-sexy.png", algorithm: "L' U' L U' R U' R'" },
  { name: "Bad Ugly", image: "/algorithms/pyraminx/l4e/l4e-bad-ugly.png", algorithm: "R U R' U L' U L" },
  { name: "Bad Righty", image: "/algorithms/pyraminx/l4e/l4e-bad-righty.png", algorithm: "L' U L U' R U R'" },
  { name: "Bad Lefty", image: "/algorithms/pyraminx/l4e/l4e-bad-lefty.png", algorithm: "R U' R' U L' U' L" },
  { name: "Double Sexy", image: "/algorithms/pyraminx/l4e/l4e-double-sexy.png", algorithm: "R U' R' U' R U R'" },
  { name: "Double Ugly", image: "/algorithms/pyraminx/l4e/l4e-double-ugly.png", algorithm: "L' U L U L' U' L" },
]
